const SECTORS = {
  "Defense & Security": { icon: "🛡️", color: "#dc2626", description: "Autonomous drones, counter-drone systems, defense AI, and next-generation weapons platforms." },
  "Nuclear Energy": { icon: "⚛️", color: "#f59e0b", description: "Small modular reactors, microreactors, nuclear fuel, and next-gen fission and fusion energy." },
  "Space & Aerospace": { icon: "🚀", color: "#3b82f6", description: "Orbital launch, satellite infrastructure, space manufacturing, and aerospace innovation." },
  "Supersonic & Hypersonic": { icon: "✈️", color: "#6366f1", description: "Supersonic jets, hypersonic vehicles, and next-generation propulsion systems." },
  "AI & Software": { icon: "🤖", color: "#8b5cf6", description: "Artificial intelligence, robotics software, and autonomous systems." },
  "Robotics & Manufacturing": { icon: "🏭", color: "#14b8a6", description: "Industrial robots, automated factories, and advanced manufacturing." },
  "Biotech & Health": { icon: "🧬", color: "#ec4899", description: "Longevity research, genomics, prosthetics, and life sciences." },
  "Climate & Energy": { icon: "🌍", color: "#22c55e", description: "Geothermal, fusion, synthetic fuels, carbon capture, and climate tech." },
  "Drones & Autonomous": { icon: "🛸", color: "#f97316", description: "Commercial drones, autonomous delivery, drone-based services, and unmanned systems." },
  "Chips & Semiconductors": { icon: "💎", color: "#06b6d4", description: "Next-gen chip architectures, photonics, quantum computing, and semiconductor innovation." },
  "Housing & Construction": { icon: "🏠", color: "#a855f7", description: "Factory-built homes, modular construction, and housing innovation." },
  "Transportation": { icon: "🚄", color: "#eab308", description: "Electric vehicles, tunneling, autonomous boats, and next-gen transport." },
  "Consumer Tech": { icon: "⚡", color: "#f43f5e", description: "AI-powered consumer products, scent tech, EdTech, and frontier consumer applications." }
};

const COMPANIES = [
  // ─── DEFENSE & SECURITY ───
  {
    name: "Anduril Industries",
    sector: "Defense & Security",
    description: "Building interoperable sensors and autonomous systems for the battlefield. Products include Roadrunner interceptor, Fury autonomous aircraft, Ghost recon drone, Copperhead AUV, and Lattice OS. Won $642M Marine Corps anti-drone contract and $1.1B Australian Navy Ghost Shark deal.",
    founder: "Palmer Luckey, Brian Schimpf, Trae Stephens",
    location: "Costa Mesa, CA",
    state: "CA",
    lat: 33.6846,
    lng: -117.8265,
    fundingStage: "Series G",
    totalRaised: "$2.5B+",
    valuation: "$30.5B",
    rosLink: "https://rationaloptimistsociety.substack.com/p/rational-optimist-awards-part-2",
    tags: ["autonomous drones", "AI", "defense", "sensors"]
  },
  {
    name: "Shield AI",
    sector: "Defense & Security",
    description: "Hivemind autonomy software that flies aircraft in swarms without GPS. Works across multiple airframes in denied environments. Dual-use AI with real-world deterrence value.",
    founder: "",
    location: "San Diego, CA",
    state: "CA",
    lat: 32.7157,
    lng: -117.1611,
    fundingStage: "Series F",
    totalRaised: "$1.4B+",
    valuation: "$5.3B",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["autonomy", "AI", "swarm", "defense"]
  },
  {
    name: "Epirus",
    sector: "Defense & Security",
    description: "High-power microwave directed energy systems for counter-drone defense. Leonidas system disables drone swarms with focused microwave energy. $250M Series D, $43.5M Army contract.",
    founder: "Andy Lowery",
    location: "Torrance, CA",
    state: "CA",
    lat: 33.8358,
    lng: -118.3406,
    fundingStage: "Series D",
    totalRaised: "$250M+",
    valuation: "$1.35B",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["directed energy", "counter-drone", "defense"]
  },
  {
    name: "Saronic",
    sector: "Defense & Security",
    description: "Autonomous surface vessels built at shipyard scale. Vertically integrated 'shipyard as startup' producing autonomous boats for naval defense on rapid cycles. $4B valuation.",
    founder: "",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    fundingStage: "Late Stage",
    totalRaised: "$500M+",
    valuation: "$4.0B",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["autonomous", "naval", "shipbuilding", "defense"]
  },
  {
    name: "Neros",
    sector: "Defense & Security",
    description: "America's leading FPV drone manufacturer. Produces ~1,000 drones monthly. Selected as US Army's primary FPV manufacturer for the Attritable Systems program. Delivered 6,000 Archer drones to Ukraine.",
    founder: "Soren Monroe-Anderson, Olaf Hichwa",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9192,
    lng: -118.4165,
    fundingStage: "Series B",
    totalRaised: "$110M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-rational-optimist-awards-2026",
    tags: ["FPV drones", "manufacturing", "defense", "Ukraine"]
  },
  {
    name: "Chaos Industries",
    sector: "Defense & Security",
    description: "Counter-drone coherent distributed networking radar systems. Raised $785M across Series C & D in 2025. ASTRIA multi-object tracking radar and partnership with Forterra.",
    founder: "John Tenet, Bo Marr",
    location: "Hawthorne, CA",
    state: "CA",
    lat: 33.9164,
    lng: -118.3526,
    fundingStage: "Series D",
    totalRaised: "$785M+",
    valuation: "$4.5B",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["radar", "counter-drone", "defense"]
  },
  {
    name: "Castelion",
    sector: "Defense & Security",
    description: "Designing and manufacturing hypersonic missiles with rapid iteration. Blackbeard weapon system integrated with US Army and Navy. $350M Series B led by Altimeter and Lightspeed.",
    founder: "Bryon Hargis",
    location: "Torrance, CA",
    state: "CA",
    lat: 33.8350,
    lng: -118.3450,
    fundingStage: "Series B",
    totalRaised: "$450M+",
    valuation: "$2.8B",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["hypersonic", "missiles", "defense"]
  },
  {
    name: "CX2 Industries",
    sector: "Defense & Security",
    description: "Advanced RF sensing systems for battlefield situational awareness. Vadris drone payload detects enemy drone pilots. Wraith drone provides electronic warfare capabilities. $31M Series A from a16z and Point72.",
    founder: "Nathan Mintz, Porter Smith",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9170,
    lng: -118.4150,
    fundingStage: "Series A",
    totalRaised: "$31M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["electronic warfare", "RF sensing", "drones", "defense"]
  },
  {
    name: "Picogrid",
    sector: "Defense & Security",
    description: "Unified data integration platform connecting sensors, end effectors, and autonomous systems. Multiple Air Force and Army contracts. Integrates with Skydio, Palantir, Northrop Grumman.",
    founder: "Zane Mountcastle",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9180,
    lng: -118.4180,
    fundingStage: "Seed",
    totalRaised: "$10M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["sensors", "integration", "autonomous", "defense"]
  },
  {
    name: "Skydio",
    sector: "Defense & Security",
    description: "Autonomous drones for defense and public safety. Only major US-made drone company. Blue UAS listed and NDAA compliant. Major defense and law enforcement contracts.",
    founder: "",
    location: "San Mateo, CA",
    state: "CA",
    lat: 37.5630,
    lng: -122.3255,
    fundingStage: "Late Stage",
    totalRaised: "$340M+",
    valuation: "$2.2B",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["autonomous drones", "public safety", "defense"]
  },
  {
    name: "Allen Control Systems",
    sector: "Defense & Security",
    description: "Bullfrog autonomous gun turret achieves ~$10 cost-per-kill against drones. Bolts onto standard military weapons. Demonstrated swarm engagement capabilities at DoD events.",
    founder: "",
    location: "Washington, DC",
    state: "DC",
    lat: 38.9072,
    lng: -77.0369,
    fundingStage: "Early Stage",
    totalRaised: "",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["counter-drone", "gun turret", "autonomous", "defense"]
  },
  {
    name: "Mach Industries",
    sector: "Defense & Security",
    description: "Advanced energetics and propulsion for defense. $100M Series B from Khosla and Bedrock. Developing VTOL cruise missiles (Viper) and propulsion systems for UAS.",
    founder: "Ethan Thornton",
    location: "Huntington Beach, CA",
    state: "CA",
    lat: 33.6603,
    lng: -117.9992,
    fundingStage: "Series B",
    totalRaised: "$100M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["missiles", "propulsion", "energetics", "defense"]
  },
  {
    name: "Andrenam",
    sector: "Defense & Security",
    description: "AI-powered distributed maritime acoustic sensing for underwater and surface security. Ex-SpaceX team. $10M Seed from First Round Capital. Participated in Navy exercises.",
    founder: "Matej Cernosek, Alex Chu",
    location: "Hawthorne, CA",
    state: "CA",
    lat: 33.9160,
    lng: -118.3530,
    fundingStage: "Seed",
    totalRaised: "$10M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["maritime", "acoustic", "sensing", "defense"]
  },
  {
    name: "Vannevar Labs",
    sector: "Defense & Security",
    description: "Intelligence, sensing, and analysis platforms for DoD competition missions. Valued at $1.5B.",
    founder: "",
    location: "Washington, DC",
    state: "DC",
    lat: 38.9100,
    lng: -77.0350,
    fundingStage: "Late Stage",
    totalRaised: "",
    valuation: "$1.5B",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["intelligence", "analysis", "defense"]
  },
  {
    name: "Blue Water Autonomy",
    sector: "Defense & Security",
    description: "Mass-producible 100ft-class unmanned ships for naval endurance missions. Raised $64M from seed through Series A for full prototype vessels.",
    founder: "",
    location: "Los Angeles, CA",
    state: "CA",
    lat: 33.9425,
    lng: -118.4081,
    fundingStage: "Series A",
    totalRaised: "$64M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["autonomous ships", "naval", "defense"]
  },

  // ─── NUCLEAR ENERGY ───
  {
    name: "Valar Atomics",
    sector: "Nuclear Energy",
    description: "First startup in history to split the atom with its own reactor core. Building gigasites with hundreds of SMRs for data center power and clean fuels. Achieved zero-power criticality at Los Alamos. $130M Series A.",
    founder: "Isaiah Taylor",
    location: "Hawthorne, CA",
    state: "CA",
    lat: 33.9164,
    lng: -118.3526,
    fundingStage: "Series A",
    totalRaised: "$149M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/introducing-our-smr-power-rankings",
    tags: ["SMR", "nuclear", "data centers", "energy"]
  },
  {
    name: "Radiant",
    sector: "Nuclear Energy",
    description: "Portable 1.2MW nuclear microreactors for austere environments and off-grid use. $300M Series D. Selected for DOE Reactor Pilot Program. 20-reactor Equinix pre-order. Air Force deployment by 2028.",
    founder: "Doug Bernauer",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9192,
    lng: -118.4165,
    fundingStage: "Series D",
    totalRaised: "$465M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/introducing-our-smr-power-rankings",
    tags: ["microreactor", "nuclear", "portable", "defense"]
  },
  {
    name: "Aalo Atomics",
    sector: "Nuclear Energy",
    description: "Pragmatic approach using off-the-shelf fuel and existing supply chains. Building test reactor in Idaho. Selected for DOE Reactor Pilot Program. Targeting July 4, 2026 activation.",
    founder: "Matt Loszak",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    fundingStage: "Series A",
    totalRaised: "$30M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/introducing-our-smr-power-rankings",
    tags: ["SMR", "nuclear", "data centers"]
  },
  {
    name: "Antares",
    sector: "Nuclear Energy",
    description: "Kilowatt-scale micro-fission reactors for defense and space. Heat pipe reactor demonstrated at Marshall Space Flight Center with NASA. $96M Series B. DOE Reactor Pilot Program selected.",
    founder: "Jordan Bramble, Julia DeWahl",
    location: "Torrance, CA",
    state: "CA",
    lat: 33.8358,
    lng: -118.3406,
    fundingStage: "Series B",
    totalRaised: "$96M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/introducing-our-smr-power-rankings",
    tags: ["microreactor", "nuclear", "defense", "space"]
  },
  {
    name: "General Matter",
    sector: "Nuclear Energy",
    description: "Rebuilding American uranium enrichment capacity for next-gen nuclear fuels. Founders Fund-incubated. $1.5B enrichment facility in Paducah, KY. $900M DOE HALEU contract.",
    founder: "Scott Nolan, Lee Robinson",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9170,
    lng: -118.4160,
    fundingStage: "Seed",
    totalRaised: "$50M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["uranium", "enrichment", "nuclear fuel", "HALEU"]
  },
  {
    name: "Kairos Power",
    sector: "Nuclear Energy",
    description: "Building molten salt microreactors for Google. Developing Hermes reactor in Oak Ridge. Targeting mid-2026 activation. Positioned as first civilian SMR deployment.",
    founder: "",
    location: "Alameda, CA",
    state: "CA",
    lat: 37.7652,
    lng: -122.2416,
    fundingStage: "Late Stage",
    totalRaised: "$500M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/introducing-our-smr-power-rankings",
    tags: ["SMR", "nuclear", "molten salt", "Google"]
  },
  {
    name: "X-Energy",
    sector: "Nuclear Energy",
    description: "SMRs for AI data centers with XENITH container reactors. $500M Amazon funding. Pentagon and Air Force contracts. 12-unit UK deployment planned.",
    founder: "",
    location: "Rockville, MD",
    state: "MD",
    lat: 39.0840,
    lng: -77.1528,
    fundingStage: "Late Stage",
    totalRaised: "$500M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/introducing-our-smr-power-rankings",
    tags: ["SMR", "nuclear", "data centers", "Amazon"]
  },
  {
    name: "Oklo",
    sector: "Nuclear Energy",
    description: "Nuclear campus and microreactors. Meta partnership in Pike County, Ohio. Equinix power agreement. Eielson Air Force Base site. Publicly traded.",
    founder: "Jacob DeWitte",
    location: "Santa Clara, CA",
    state: "CA",
    lat: 37.3541,
    lng: -121.9552,
    fundingStage: "Public",
    totalRaised: "",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/introducing-our-smr-power-rankings",
    tags: ["SMR", "nuclear", "data centers", "Meta"]
  },
  {
    name: "Last Energy",
    sector: "Nuclear Energy",
    description: "Building microreactors in UK and Texas. £80M UK deal with grid connection approval. Haskell County, Texas data center deal.",
    founder: "",
    location: "Washington, DC",
    state: "DC",
    lat: 38.9072,
    lng: -77.0369,
    fundingStage: "Series A",
    totalRaised: "$80M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/introducing-our-smr-power-rankings",
    tags: ["microreactor", "nuclear", "UK", "data centers"]
  },
  {
    name: "Deep Fission",
    sector: "Nuclear Energy",
    description: "Underground microreactors deployed in one-mile-deep boreholes. $30M funding. Letters of Intent for Texas, Utah, Kansas. DOE Pilot Program selection.",
    founder: "",
    location: "Houston, TX",
    state: "TX",
    lat: 29.7604,
    lng: -95.3698,
    fundingStage: "Seed",
    totalRaised: "$30M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/introducing-our-smr-power-rankings",
    tags: ["underground", "nuclear", "borehole"]
  },
  {
    name: "TerraPower",
    sector: "Nuclear Energy",
    description: "Building Natrium reactors in Kemmerer, Wyoming. Meta funding for two reactors. NRC final safety evaluation completed. Bill Gates-backed.",
    founder: "",
    location: "Bellevue, WA",
    state: "WA",
    lat: 47.6101,
    lng: -122.2015,
    fundingStage: "Late Stage",
    totalRaised: "$1B+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/introducing-our-smr-power-rankings",
    tags: ["SMR", "nuclear", "Natrium"]
  },
  {
    name: "Standard Nuclear",
    sector: "Nuclear Energy",
    description: "Nuclear reactor company based in Tennessee, developing standardized reactor designs for rapid deployment.",
    founder: "Jonathan Webb",
    location: "Nashville, TN",
    state: "TN",
    lat: 36.1627,
    lng: -86.7816,
    fundingStage: "Early Stage",
    totalRaised: "",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["nuclear", "standardized", "reactors"]
  },

  // ─── SPACE & AEROSPACE ───
  {
    name: "SpaceX",
    sector: "Space & Aerospace",
    description: "The defining space company of the generation. 165 Falcon 9 launches in 2025, responsible for 81% of all mass launched to orbit. Starlink serves 9M+ customers in 155+ countries. Preparing for IPO at $1.5T valuation.",
    founder: "Elon Musk",
    location: "Hawthorne, CA",
    state: "CA",
    lat: 33.9207,
    lng: -118.3280,
    fundingStage: "Late Stage",
    totalRaised: "$10B+",
    valuation: "$800B",
    rosLink: "https://rationaloptimistsociety.substack.com/p/rational-optimist-awards-part-2",
    tags: ["rockets", "satellites", "Starlink", "space"]
  },
  {
    name: "Rocket Lab",
    sector: "Space & Aerospace",
    description: "Only company besides SpaceX successfully launching payloads to orbit. 18 successful Electron launches in 2025. Won $816M SDA missile defense satellite contract. Market cap tripled to $37B.",
    founder: "Peter Beck",
    location: "Long Beach, CA",
    state: "CA",
    lat: 33.7701,
    lng: -118.1937,
    fundingStage: "Public",
    totalRaised: "",
    valuation: "$45B",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["rockets", "satellites", "launch"]
  },
  {
    name: "Apex Space",
    sector: "Space & Aerospace",
    description: "The 'Foxconn of satellite buses.' Standardized, configurable satellite platforms with transparent pricing. $45.9M Space Force contract. $400M in Series C+D funding. Producing 200+ satellites/year.",
    founder: "Ian Cinnamon, Max Benassi",
    location: "Playa Vista, CA",
    state: "CA",
    lat: 33.9745,
    lng: -118.4280,
    fundingStage: "Series D",
    totalRaised: "$400M+",
    valuation: "$1B+",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["satellite buses", "manufacturing", "space"]
  },
  {
    name: "Varda Space Industries",
    sector: "Space & Aerospace",
    description: "Manufacturing pharmaceuticals in microgravity and returning them to Earth via re-entry capsules. Launched 5 missions in 2025. $187M Series C from Founders Fund, Khosla, Lux Capital.",
    founder: "Will Bruey, Delian Asparouhov",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9200,
    lng: -118.4160,
    fundingStage: "Series C",
    totalRaised: "$187M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-rational-optimist-awards-2026",
    tags: ["space manufacturing", "pharmaceuticals", "re-entry"]
  },
  {
    name: "AstroForge",
    sector: "Space & Aerospace",
    description: "Asteroid mining satellites targeting platinum-group metals. Building technology to make space resources commercially viable.",
    founder: "",
    location: "Huntington Beach, CA",
    state: "CA",
    lat: 33.6595,
    lng: -117.9988,
    fundingStage: "Series A",
    totalRaised: "$55M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-rational-optimist-awards-2026",
    tags: ["asteroid mining", "platinum", "space resources"]
  },
  {
    name: "Reflect Orbital",
    sector: "Space & Aerospace",
    description: "Constellation of reflective satellites delivering targeted sunlight to Earth at night. $20M Series A from Lux and Sequoia. 260,000+ applications from 157 countries.",
    founder: "Ben Nowack, Tristan Semmelhack",
    location: "Hawthorne, CA",
    state: "CA",
    lat: 33.9165,
    lng: -118.3535,
    fundingStage: "Series A",
    totalRaised: "$20M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["reflected sunlight", "satellites", "space"]
  },
  {
    name: "Relativity Space",
    sector: "Space & Aerospace",
    description: "Heavy-lift partially reusable orbital launch vehicle. Eric Schmidt bought majority stake and became CEO. Moving into space-based data center market.",
    founder: "Eric Schmidt (CEO), Kevin Wu",
    location: "Long Beach, CA",
    state: "CA",
    lat: 33.7700,
    lng: -118.1940,
    fundingStage: "Late Stage",
    totalRaised: "$1.3B+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["rockets", "launch", "3D printing"]
  },
  {
    name: "Impulse Space",
    sector: "Space & Aerospace",
    description: "Orbital kickstage for last-mile payload delivery and high-maneuverability satellite buses. Successfully launched 3 missions. $300M Series C from Founders Fund, Lux, RTX.",
    founder: "Tom Mueller",
    location: "Redondo Beach, CA",
    state: "CA",
    lat: 33.8492,
    lng: -118.3884,
    fundingStage: "Series C",
    totalRaised: "$300M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["orbital transfer", "satellite buses", "space"]
  },
  {
    name: "K2 Space",
    sector: "Space & Aerospace",
    description: "Leveraging cheap heavy-lift launch to build larger satellite buses. Mega-class (30kW) and Giga-class (110kW) satellites. $360M raised. $500M+ in signed contracts.",
    founder: "Karan Kunjur, Neel Kunjur",
    location: "Torrance, CA",
    state: "CA",
    lat: 33.8360,
    lng: -118.3410,
    fundingStage: "Series C",
    totalRaised: "$360M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["large satellites", "heavy-lift", "space"]
  },
  {
    name: "Vast",
    sector: "Space & Aerospace",
    description: "Building the world's first commercial space station. Haven Demo launched Nov 2025 on SpaceX rideshare. Haven-1 targeted for May 2026 launch. In-Q-Tel investment.",
    founder: "Max Haot, Jed McCaleb",
    location: "Long Beach, CA",
    state: "CA",
    lat: 33.7705,
    lng: -118.1942,
    fundingStage: "Private",
    totalRaised: "$300M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["space station", "commercial space", "LEO"]
  },
  {
    name: "Northwood Space",
    sector: "Space & Aerospace",
    description: "Phased array ground stations for rapid satellite data transmission. $30M Series A from a16z and Alpine Space Ventures. Expanding ground network to 6 continents.",
    founder: "Bridgit Mendler, Griffin Cleverly",
    location: "Torrance, CA",
    state: "CA",
    lat: 33.8355,
    lng: -118.3415,
    fundingStage: "Series A",
    totalRaised: "$30M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["ground stations", "satellite comms", "space"]
  },
  {
    name: "Astranis",
    sector: "Space & Aerospace",
    description: "Small geostationary satellites that deliver affordable internet to underserved regions. MicroGEO satellites where fiber doesn't reach.",
    founder: "John Gedmark",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    fundingStage: "Late Stage",
    totalRaised: "$350M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["GEO satellites", "internet", "connectivity"]
  },
  {
    name: "Observable Space",
    sector: "Space & Aerospace",
    description: "Ground-based telescope systems and space optics for space domain awareness and laser communications. Serves NASA, Space Force, Raytheon, Northrop Grumman.",
    founder: "Dan Roelker, Rick Hedrick",
    location: "Los Angeles, CA",
    state: "CA",
    lat: 34.0522,
    lng: -118.2437,
    fundingStage: "Series A",
    totalRaised: "$20M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["telescopes", "space awareness", "optics"]
  },
  {
    name: "Firefly Aerospace",
    sector: "Space & Aerospace",
    description: "Small launch vehicle company providing responsive launch services. Alpha rocket for small payloads and Miranda spacecraft for orbital operations.",
    founder: "",
    location: "Cedar Park, TX",
    state: "TX",
    lat: 30.5052,
    lng: -97.8203,
    fundingStage: "Late Stage",
    totalRaised: "$300M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["rockets", "small launch", "space"]
  },
  {
    name: "Intuitive Machines",
    sector: "Space & Aerospace",
    description: "Lunar lander and space services company. First American company to land on the Moon in over 50 years with Nova-C lander. Multiple NASA CLPS contracts.",
    founder: "",
    location: "Houston, TX",
    state: "TX",
    lat: 29.7604,
    lng: -95.3698,
    fundingStage: "Public",
    totalRaised: "",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["Moon", "lunar lander", "NASA"]
  },

  // ─── SUPERSONIC & HYPERSONIC ───
  {
    name: "Boom Supersonic",
    sector: "Supersonic & Hypersonic",
    description: "Designing and building the Overture supersonic commercial jet. Created the XB-1 test jet. Designing proprietary Symphony engine. 130+ orders from airlines.",
    founder: "Blake Scholl",
    location: "Denver, CO",
    state: "CO",
    lat: 39.7392,
    lng: -104.9903,
    fundingStage: "Late Stage",
    totalRaised: "$700M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/dude-wheres-my-supersonic-jet",
    tags: ["supersonic", "aviation", "commercial jets"]
  },
  {
    name: "Hermeus",
    sector: "Supersonic & Hypersonic",
    description: "Building Mach 5 hypersonic jets with hybrid Chimera engine. Quarterhorse test program with escalating aircraft. First jet flew May 2024. Military applications first.",
    founder: "AJ Piplica",
    location: "Atlanta, GA",
    state: "GA",
    lat: 33.7490,
    lng: -84.3880,
    fundingStage: "Series C",
    totalRaised: "$200M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/dude-wheres-my-supersonic-jet",
    tags: ["hypersonic", "Mach 5", "military", "aviation"]
  },
  {
    name: "Astro Mechanica",
    sector: "Supersonic & Hypersonic",
    description: "Electric Adaptive Engine for supersonic flight that transitions from turbofan to ramjet. Planning Uber-style on-demand supersonic flights with LNG fuel. $27M raised. United Airlines invested.",
    founder: "Ian Brooke",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    fundingStage: "Series A",
    totalRaised: "$27M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/dude-wheres-my-supersonic-jet",
    tags: ["supersonic", "electric engine", "adaptive", "aviation"]
  },
  {
    name: "Venus Aerospace",
    sector: "Supersonic & Hypersonic",
    description: "Developing hypersonic vehicles capable of Mach 9+ speeds for both commercial and defense applications.",
    founder: "Sassie Duggleby",
    location: "Houston, TX",
    state: "TX",
    lat: 29.7604,
    lng: -95.3698,
    fundingStage: "Series B",
    totalRaised: "$44M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["hypersonic", "Mach 9", "aviation"]
  },

  // ─── AI & SOFTWARE ───
  {
    name: "Physical Intelligence",
    sector: "AI & Software",
    description: "AI foundation model for robotics. Building general-purpose robot intelligence that enables physical manipulation and interaction. Major Bay Area robotics lab.",
    founder: "",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    fundingStage: "Series A",
    totalRaised: "$400M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["AI", "robotics", "foundation model"]
  },
  {
    name: "Waymo",
    sector: "AI & Software",
    description: "Autonomous robotaxi service operating in Austin, LA, and San Francisco. 1 million rides per month in California. 90%+ fewer crashes than human drivers.",
    founder: "",
    location: "Mountain View, CA",
    state: "CA",
    lat: 37.3861,
    lng: -122.0839,
    fundingStage: "Alphabet subsidiary",
    totalRaised: "$5.5B+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/rational-optimist-awards-part-2",
    tags: ["autonomous vehicles", "robotaxi", "AI"]
  },
  {
    name: "Figure AI",
    sector: "AI & Software",
    description: "General-purpose humanoid robots for industrial applications. $675M raise from Microsoft, OpenAI, NVIDIA, Bezos. Deployed at BMW plant. Fastest-moving team in humanoids.",
    founder: "Brett Adcock",
    location: "San Jose, CA",
    state: "CA",
    lat: 37.3382,
    lng: -121.8863,
    fundingStage: "Series B",
    totalRaised: "$675M+",
    valuation: "$2.6B",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["humanoid robots", "AI", "manufacturing"]
  },
  {
    name: "Neuralink",
    sector: "AI & Software",
    description: "Brain-computer interface implants with quarter-sized chip and 1,024 microscopic electrodes. First regional trial launched. Enabling ALS patients to control devices with thought.",
    founder: "Elon Musk",
    location: "Fremont, CA",
    state: "CA",
    lat: 37.5485,
    lng: -121.9886,
    fundingStage: "Late Stage",
    totalRaised: "$500M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/rational-optimist-awards-part-2",
    tags: ["BCI", "neuroscience", "AI", "implants"]
  },
  {
    name: "Field AI",
    sector: "AI & Software",
    description: "General-purpose embodied AI foundation models for robots in complex industrial environments. $405M raised at $2B valuation. SoCal's own robotics lab to rival Bay Area.",
    founder: "Ali Agha",
    location: "Irvine, CA",
    state: "CA",
    lat: 33.6846,
    lng: -117.8265,
    fundingStage: "Series A",
    totalRaised: "$405M",
    valuation: "$2B",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["embodied AI", "robotics", "foundation models"]
  },
  {
    name: "Nominal",
    sector: "AI & Software",
    description: "Engineering observability platform for hardware testing, reliability, and performance monitoring. $75M Series B from Sequoia. 10x revenue growth and 6x customer growth YoY.",
    founder: "Cameron McCord, Bryce Strauss",
    location: "Culver City, CA",
    state: "CA",
    lat: 34.0211,
    lng: -118.3965,
    fundingStage: "Series B",
    totalRaised: "$75M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["engineering", "observability", "testing"]
  },
  {
    name: "Palantir",
    sector: "AI & Software",
    description: "Data analytics and AI platform for government and commercial applications. Foundry, Gotham, and AIP platforms. Maven Smart System for defense.",
    founder: "Peter Thiel, Alex Karp",
    location: "Denver, CO",
    state: "CO",
    lat: 39.7392,
    lng: -104.9903,
    fundingStage: "Public",
    totalRaised: "",
    valuation: "$150B+",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["data analytics", "AI", "defense", "government"]
  },
  {
    name: "Cognition",
    sector: "AI & Software",
    description: "Building Devin, the world's first AI software engineer. Autonomous coding agent that can plan, write, debug, and deploy software end-to-end.",
    founder: "",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7755,
    lng: -122.4180,
    fundingStage: "Series A",
    totalRaised: "$175M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["AI", "coding", "autonomous agent"]
  },

  // ─── ROBOTICS & MANUFACTURING ───
  {
    name: "Hadrian",
    sector: "Robotics & Manufacturing",
    description: "Software-defined automated factories producing high-precision machined parts for aerospace and defense. $260M Series C. Expanding to 270,000 sq ft Mesa, AZ facility. Moving into maritime and munitions.",
    founder: "Chris Power",
    location: "Torrance, CA",
    state: "CA",
    lat: 33.8358,
    lng: -118.3406,
    fundingStage: "Series C",
    totalRaised: "$260M+",
    valuation: "$1.6B",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["automated factory", "CNC", "aerospace", "defense"]
  },
  {
    name: "Machina Labs",
    sector: "Robotics & Manufacturing",
    description: "Giant robotic arms that automate metal forming and manufacturing. Roboforming technology. Toyota partnership for auto body panels. $35M Abu Dhabi investment. Air Force contract.",
    founder: "Ed Mehr",
    location: "Chatsworth, CA",
    state: "CA",
    lat: 34.2572,
    lng: -118.6012,
    fundingStage: "Series B",
    totalRaised: "$80M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["robotic manufacturing", "metal forming", "automotive"]
  },
  {
    name: "Formic",
    sector: "Robotics & Manufacturing",
    description: "Robots-as-a-service for manufacturing. Making industrial robots accessible to small and medium manufacturers through a pay-per-use model.",
    founder: "",
    location: "Chicago, IL",
    state: "IL",
    lat: 41.8781,
    lng: -87.6298,
    fundingStage: "Series A",
    totalRaised: "$56M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["robots-as-a-service", "manufacturing", "automation"]
  },
  {
    name: "Rangeview",
    sector: "Robotics & Manufacturing",
    description: "Automated foundry using robotics and materials science for investment casting of metal parts. Air Force SBIR for turbine components. Expanded El Segundo facility.",
    founder: "Cameron Schiller, Aeden Gasser-Brennan",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9185,
    lng: -118.4155,
    fundingStage: "Seed",
    totalRaised: "$5M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["casting", "foundry", "robotics", "manufacturing"]
  },
  {
    name: "Senra Systems",
    sector: "Robotics & Manufacturing",
    description: "Software-defined manufacturing of complex wire harnesses. $25M Series A co-led by Figma CEO and CIV. Investors include Sequoia, a16z, Founders Fund.",
    founder: "Jordan Black, Ben Shanahan",
    location: "Redondo Beach, CA",
    state: "CA",
    lat: 33.8495,
    lng: -118.3880,
    fundingStage: "Series A",
    totalRaised: "$25M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["wire harnesses", "manufacturing", "software-defined"]
  },
  {
    name: "Salient Motion",
    sector: "Robotics & Manufacturing",
    description: "Critical actuation and motion control components for commercial aviation and defense. Components on active military aircraft. Working on first FAA-certified system for Boeing and Airbus.",
    founder: "Vishaal Mali",
    location: "Torrance, CA",
    state: "CA",
    lat: 33.8365,
    lng: -118.3420,
    fundingStage: "Seed",
    totalRaised: "$10M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["actuation", "motion control", "aviation"]
  },
  {
    name: "Divergent",
    sector: "Robotics & Manufacturing",
    description: "End-to-end additive manufacturing for automotive, aerospace, and defense. $290M Series E at $2.3B valuation. Partnerships with Lockheed Martin, Raytheon, General Atomics, Saab.",
    founder: "Lukas Czinger, Kevin Czinger",
    location: "Torrance, CA",
    state: "CA",
    lat: 33.8370,
    lng: -118.3425,
    fundingStage: "Series E",
    totalRaised: "$600M+",
    valuation: "$2.3B",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["additive manufacturing", "automotive", "defense"]
  },
  {
    name: "Amca",
    sector: "Robotics & Manufacturing",
    description: "Acquiring and modernizing legacy aerospace component suppliers. $76.5M from Caffeinated Capital, Founders Fund, Lux, a16z. Acquired four component suppliers.",
    founder: "Jai Malik, Eli Giovanetti",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9175,
    lng: -118.4145,
    fundingStage: "Series A",
    totalRaised: "$76.5M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["acquisitions", "aerospace components", "manufacturing"]
  },

  // ─── BIOTECH & HEALTH ───
  {
    name: "Altos Labs",
    sector: "Biotech & Health",
    description: "Cell reprogramming and rejuvenation research. $3 billion Jeff Bezos-backed startup. Using cyclic OSKM expression to reverse cellular aging. Labs in US, UK, Japan.",
    founder: "",
    location: "San Carlos, CA",
    state: "CA",
    lat: 37.5072,
    lng: -122.2605,
    fundingStage: "Late Stage",
    totalRaised: "$3B",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/cracking-the-methuselah-code",
    tags: ["longevity", "cell reprogramming", "aging"]
  },
  {
    name: "Retro Biosciences",
    sector: "Biotech & Health",
    description: "Targeting three core aging 'bugs': toxic blood molecules, genetic errors, and cellular cleanup. RTR-242 drug targets autophagy. Sam Altman invested $180M.",
    founder: "",
    location: "Redwood City, CA",
    state: "CA",
    lat: 37.4852,
    lng: -122.2364,
    fundingStage: "Series A",
    totalRaised: "$180M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/cracking-the-methuselah-code",
    tags: ["longevity", "aging", "autophagy"]
  },
  {
    name: "New Limit",
    sector: "Biotech & Health",
    description: "Finding safer transcription factor combinations for cellular reprogramming using AI. Co-founded by Brian Armstrong (Coinbase) and Blake Byers. Peter Thiel, Eric Schmidt investors.",
    founder: "Brian Armstrong, Blake Byers",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    fundingStage: "Series A",
    totalRaised: "$40M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/cracking-the-methuselah-code",
    tags: ["longevity", "epigenetics", "AI"]
  },
  {
    name: "Atom Bodies",
    sector: "Biotech & Health",
    description: "AI-powered prosthetic arms with 26 degrees of finger freedom. Uses LLMs to interpret nerve signals. Takes just 5 minutes to teach the arm. Restoring dexterity and dignity.",
    founder: "Tyler Hayes",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7740,
    lng: -122.4200,
    fundingStage: "Series A",
    totalRaised: "$20M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/ridley-america-recharged-my-optimism",
    tags: ["prosthetics", "AI", "bionics"]
  },
  {
    name: "Mammoth Biosciences",
    sector: "Biotech & Health",
    description: "CRISPR-based diagnostics and therapeutics company. Next-generation gene editing platform with novel Cas enzymes for both detection and treatment.",
    founder: "",
    location: "Brisbane, CA",
    state: "CA",
    lat: 37.6808,
    lng: -122.4000,
    fundingStage: "Series D",
    totalRaised: "$600M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["CRISPR", "gene editing", "diagnostics"]
  },
  {
    name: "Nucleus Genomics",
    sector: "Biotech & Health",
    description: "Personalized disease risk assessment and embryo screening using advanced genomics and AI-powered analysis.",
    founder: "",
    location: "New York, NY",
    state: "NY",
    lat: 40.7128,
    lng: -74.0060,
    fundingStage: "Series A",
    totalRaised: "$20M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["genomics", "disease risk", "screening"]
  },
  {
    name: "Orchid",
    sector: "Biotech & Health",
    description: "Embryo screening and reproductive genomics platform that helps parents select for healthier embryos using whole genome sequencing.",
    founder: "",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7760,
    lng: -122.4190,
    fundingStage: "Series A",
    totalRaised: "$25M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["genomics", "embryo screening", "reproductive"]
  },

  // ─── CLIMATE & ENERGY ───
  {
    name: "Terraform Industries",
    sector: "Climate & Energy",
    description: "Modular synthetic fuel production from solar energy and air. Terraformer converts sunlight + CO2 into pipeline-grade methane. Demonstrated 99.4% purity. $26M raised.",
    founder: "Casey Handmer",
    location: "Burbank, CA",
    state: "CA",
    lat: 34.1808,
    lng: -118.3090,
    fundingStage: "Series A",
    totalRaised: "$26M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["synthetic fuel", "carbon capture", "solar"]
  },
  {
    name: "Commonwealth Fusion Systems",
    sector: "Climate & Energy",
    description: "Compact tokamak fusion using high-temperature superconducting magnets. Nearly $3 billion raised. Targeting net energy generation by 2027.",
    founder: "",
    location: "Devens, MA",
    state: "MA",
    lat: 42.5473,
    lng: -71.6133,
    fundingStage: "Late Stage",
    totalRaised: "$3B",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/ridley-are-we-finally-about-to-crack",
    tags: ["fusion", "tokamak", "superconductors"]
  },
  {
    name: "Fervo Energy",
    sector: "Climate & Energy",
    description: "Next-gen geothermal energy using precision-drilled L-shaped wells into hot granite. Reducing drilling times by 70% year-over-year. Utah desert operations.",
    founder: "",
    location: "Houston, TX",
    state: "TX",
    lat: 29.7604,
    lng: -95.3698,
    fundingStage: "Series C",
    totalRaised: "$430M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/how-many-lives-will-this-ai-model",
    tags: ["geothermal", "drilling", "clean energy"]
  },
  {
    name: "Xcimer Energy",
    sector: "Climate & Energy",
    description: "Inertial confinement fusion using massive lasers to fire at falling fuel capsules. Colorado-based approach to commercial fusion energy.",
    founder: "",
    location: "Denver, CO",
    state: "CO",
    lat: 39.7392,
    lng: -104.9903,
    fundingStage: "Series A",
    totalRaised: "$100M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/ridley-are-we-finally-about-to-crack",
    tags: ["fusion", "laser", "inertial confinement"]
  },
  {
    name: "Helion",
    sector: "Climate & Energy",
    description: "Field-reversed configuration plasma fusion. Washington state-based. Developing compact fusion approach with direct electricity conversion.",
    founder: "",
    location: "Everett, WA",
    state: "WA",
    lat: 47.9790,
    lng: -122.2021,
    fundingStage: "Late Stage",
    totalRaised: "$600M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/ridley-are-we-finally-about-to-crack",
    tags: ["fusion", "field-reversed", "energy"]
  },
  {
    name: "TAE Technologies",
    sector: "Climate & Energy",
    description: "Field-reversed configuration fusion using proton-boron fuel. Partnered with Japan's NIFS. First proton-boron fusion in magnetically confined plasma.",
    founder: "",
    location: "Foothill Ranch, CA",
    state: "CA",
    lat: 33.6854,
    lng: -117.6611,
    fundingStage: "Late Stage",
    totalRaised: "$1.2B+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/ridley-are-we-finally-about-to-crack",
    tags: ["fusion", "proton-boron", "energy"]
  },
  {
    name: "Mazama",
    sector: "Climate & Energy",
    description: "Supercritical geothermal technology. Drilled the hottest geothermal well in history at Newberry Volcano in Oregon.",
    founder: "",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2680,
    lng: -97.7440,
    fundingStage: "Series A",
    totalRaised: "$30M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/how-many-lives-will-this-ai-model",
    tags: ["geothermal", "supercritical", "energy"]
  },
  {
    name: "Quaise Energy",
    sector: "Climate & Energy",
    description: "Laser-based 'energy drill' using millimeter waves to melt rock. Targeting 12-mile-deep wells. Founded at MIT nuclear fusion lab.",
    founder: "",
    location: "Cambridge, MA",
    state: "MA",
    lat: 42.3601,
    lng: -71.0589,
    fundingStage: "Series A",
    totalRaised: "$75M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/how-many-lives-will-this-ai-model",
    tags: ["geothermal", "deep drilling", "millimeter wave"]
  },
  {
    name: "Captura",
    sector: "Climate & Energy",
    description: "Ocean-based carbon removal technology. Uses electrochemical process to capture CO2 from seawater, which absorbs 30% of atmospheric carbon.",
    founder: "",
    location: "Los Angeles, CA",
    state: "CA",
    lat: 34.0522,
    lng: -118.2437,
    fundingStage: "Series A",
    totalRaised: "$30M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["carbon capture", "ocean", "climate"]
  },
  {
    name: "Base Power",
    sector: "Climate & Energy",
    description: "Building virtual power plants with batteries. Providing distributed energy storage to create grid-scale power from residential batteries.",
    founder: "",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2675,
    lng: -97.7435,
    fundingStage: "Series A",
    totalRaised: "$50M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["virtual power plant", "batteries", "energy"]
  },
  {
    name: "Karman Industries",
    sector: "Climate & Energy",
    description: "Advanced electric heat pumps inspired by rocket turbomachinery to replace industrial boilers. $7.5M Seed from Riot Ventures.",
    founder: "David Tearse, Chiranjeev Kalra",
    location: "Long Beach, CA",
    state: "CA",
    lat: 33.7710,
    lng: -118.1945,
    fundingStage: "Seed",
    totalRaised: "$7.5M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["heat pumps", "industrial", "decarbonization"]
  },
  {
    name: "Claros",
    sector: "Climate & Energy",
    description: "Power management technology for data center efficiency. Proprietary integrated voltage regulators to improve power consumption and minimize heat loss. $9.75M seed.",
    founder: "Daniel Kultran, Grant Verstandig",
    location: "Torrance, CA",
    state: "CA",
    lat: 33.8375,
    lng: -118.3430,
    fundingStage: "Seed",
    totalRaised: "$9.75M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["power management", "data centers", "efficiency"]
  },

  // ─── DRONES & AUTONOMOUS ───
  {
    name: "Zipline",
    sector: "Drones & Autonomous",
    description: "World's most mature autonomous delivery system. Delivers 70% of Rwanda's blood supply. 120+ million autonomous miles flown. Walmart and Chipotle partnerships in Dallas.",
    founder: "",
    location: "South San Francisco, CA",
    state: "CA",
    lat: 37.6547,
    lng: -122.4077,
    fundingStage: "Late Stage",
    totalRaised: "$600M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-rational-optimist-awards-2026",
    tags: ["delivery drones", "medical", "autonomous"]
  },
  {
    name: "Joby Aviation",
    sector: "Drones & Autonomous",
    description: "Electric vertical takeoff and landing (eVTOL) air taxi. Operating in UAE. Leading the urban air mobility revolution with certified electric aircraft.",
    founder: "JoeBen Bevirt",
    location: "Santa Cruz, CA",
    state: "CA",
    lat: 36.9741,
    lng: -122.0308,
    fundingStage: "Public",
    totalRaised: "$2B+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["eVTOL", "air taxi", "electric aviation"]
  },
  {
    name: "Rainmaker",
    sector: "Drones & Autonomous",
    description: "Drone-enabled cloud seeding for water scarcity. Running the largest cloud seeding program in modern US history in Utah. $25M Series A from Lowercarbon Capital.",
    founder: "Augustus Doricko",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9188,
    lng: -118.4162,
    fundingStage: "Series A",
    totalRaised: "$25M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["cloud seeding", "weather modification", "water"]
  },
  {
    name: "Thoron",
    sector: "Drones & Autonomous",
    description: "American drone manufacturer positioned as the alternative to China's DJI. Building the domestic commercial drone supply chain.",
    founder: "Thayne Kollmorgen",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    fundingStage: "Early Stage",
    totalRaised: "",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["commercial drones", "DJI alternative", "manufacturing"]
  },
  {
    name: "Airship Industries",
    sector: "Drones & Autonomous",
    description: "Next-generation blimp and airship technology for cargo transport, surveillance, and communication relay. Reimagining lighter-than-air vehicles.",
    founder: "",
    location: "Los Angeles, CA",
    state: "CA",
    lat: 34.0530,
    lng: -118.2440,
    fundingStage: "Early Stage",
    totalRaised: "",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["airships", "blimps", "cargo"]
  },

  // ─── CHIPS & SEMICONDUCTORS ───
  {
    name: "Cerebras",
    sector: "Chips & Semiconductors",
    description: "World's largest computer chips, dinner plate-sized with 4+ trillion transistors. Designed specifically for running AI models at unprecedented speed.",
    founder: "",
    location: "Sunnyvale, CA",
    state: "CA",
    lat: 37.3688,
    lng: -122.0363,
    fundingStage: "Late Stage",
    totalRaised: "$700M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-chip-rebellion-is-on",
    tags: ["AI chips", "wafer-scale", "semiconductors"]
  },
  {
    name: "Etched",
    sector: "Chips & Semiconductors",
    description: "Specialized AI chips with rules physically burned into silicon. One server replaces 160 NVIDIA GPUs. Founded by two Harvard dropouts. $5B valuation.",
    founder: "",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    fundingStage: "Series A",
    totalRaised: "$125M+",
    valuation: "$5B",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-chip-rebellion-is-on",
    tags: ["AI chips", "ASIC", "inference"]
  },
  {
    name: "Extropic",
    sector: "Chips & Semiconductors",
    description: "Thermodynamic computing chips that harness natural 'noise' as an energy source. Claims 10,000x energy efficiency improvement. Debuting TSUs in 2026.",
    founder: "Gill Verdon",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7755,
    lng: -122.4190,
    fundingStage: "Series A",
    totalRaised: "$50M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-chip-rebellion-is-on",
    tags: ["thermodynamic computing", "AI chips", "energy efficient"]
  },
  {
    name: "Lightmatter",
    sector: "Chips & Semiconductors",
    description: "Replaces copper wires with fiber-optic technology to move data as light between chips. Eliminates heat generation. Shoots 16 colors of light simultaneously.",
    founder: "",
    location: "Boston, MA",
    state: "MA",
    lat: 42.3601,
    lng: -71.0589,
    fundingStage: "Series C",
    totalRaised: "$420M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-chip-rebellion-is-on",
    tags: ["photonic interconnects", "optical", "chips"]
  },
  {
    name: "Substrate",
    sector: "Chips & Semiconductors",
    description: "X-ray lithography chipmaking machines to print transistors more precisely than current UV methods. Aims to cut cutting-edge wafer costs from $100K to $10K.",
    founder: "James Proud",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7752,
    lng: -122.4185,
    fundingStage: "Series A",
    totalRaised: "$30M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-chip-rebellion-is-on",
    tags: ["lithography", "X-ray", "chipmaking"]
  },
  {
    name: "Lab 91",
    sector: "Chips & Semiconductors",
    description: "2D semiconductor chips using Molybdenum Disulfide instead of silicon. Initially focused on RF Switches for 5G radio signals in phones.",
    founder: "",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    fundingStage: "Seed",
    totalRaised: "$10M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-chip-rebellion-is-on",
    tags: ["2D materials", "MoS2", "5G", "semiconductors"]
  },

  // ─── HOUSING & CONSTRUCTION ───
  {
    name: "Cuby Technologies",
    sector: "Housing & Construction",
    description: "Mobile Micro-Factories that manufacture homes from 'kits of parts.' Portable factories packed into ~122 shipping containers. First US factory in Las Vegas. FactoryOS software.",
    founder: "Aleks Gampel, Aleh Kandrashou",
    location: "Las Vegas, NV",
    state: "NV",
    lat: 36.1699,
    lng: -115.1398,
    fundingStage: "Series A",
    totalRaised: "$50M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-american-dream-needs-a-factory",
    tags: ["modular homes", "micro-factory", "construction"]
  },
  {
    name: "Cover",
    sector: "Housing & Construction",
    description: "Factory-manufactured, panel-based modular construction. Built the first custom home rebuild after the Pacific Palisades fires, demonstrating speed and versatility.",
    founder: "Alexis Rivas",
    location: "Gardena, CA",
    state: "CA",
    lat: 33.8883,
    lng: -118.3090,
    fundingStage: "Series B",
    totalRaised: "$100M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["modular homes", "panel-based", "construction"]
  },

  // ─── TRANSPORTATION ───
  {
    name: "The Boring Company",
    sector: "Transportation",
    description: "Underground car tunnels and transit systems. Built miles of tunnels under the Las Vegas Convention Center in 18 months. 35,000 passengers daily.",
    founder: "Elon Musk",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    fundingStage: "Late Stage",
    totalRaised: "$675M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/ridley-america-recharged-my-optimism",
    tags: ["tunneling", "transit", "infrastructure"]
  },
  {
    name: "Pipedream",
    sector: "Transportation",
    description: "Underground hyperlogistics network using small-diameter pipes to deliver packages at high speed beneath cities. Reimagining last-mile delivery infrastructure.",
    founder: "",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2678,
    lng: -97.7442,
    fundingStage: "Series A",
    totalRaised: "$30M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["underground delivery", "logistics", "infrastructure"]
  },
  {
    name: "Navier",
    sector: "Transportation",
    description: "Electric hydrofoil boats that fly above the water on foils. Eliminating wave drag for dramatically more efficient water transport.",
    founder: "",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    fundingStage: "Series A",
    totalRaised: "$20M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["electric boats", "hydrofoil", "maritime"]
  },
  {
    name: "Arc Boats",
    sector: "Transportation",
    description: "High-performance electric boats combining cutting-edge battery technology with advanced marine design.",
    founder: "Mitch Lee",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7745,
    lng: -122.4200,
    fundingStage: "Series B",
    totalRaised: "$70M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["electric boats", "marine", "batteries"]
  },

  // ─── CONSUMER TECH ───
  {
    name: "Osmo Labs",
    sector: "Consumer Tech",
    description: "First company to 'teleport' a scent digitally. Scent digitization and AI-powered fragrance creation. Giving computers a sense of smell.",
    founder: "Alex Wiltschko",
    location: "New York, NY",
    state: "NY",
    lat: 40.7549,
    lng: -73.9840,
    fundingStage: "Series A",
    totalRaised: "$60M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-rational-optimist-awards-2026",
    tags: ["scent", "digital smell", "AI"]
  },
  {
    name: "Alpha School",
    sector: "Consumer Tech",
    description: "Revolutionary K-12 education with two-hour school days enabled by AI-powered personalized learning. Students consistently outperform traditional schools.",
    founder: "MacKenzie Price",
    location: "Austin, TX",
    state: "TX",
    lat: 30.2672,
    lng: -97.7431,
    fundingStage: "Early Stage",
    totalRaised: "",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/the-rational-optimist-awards-2026",
    tags: ["education", "AI", "school"]
  },
  {
    name: "Matic Robotics",
    sector: "Consumer Tech",
    description: "Autonomous robot vacuum with AI mapping and navigation. Advanced computer vision for intelligent home cleaning.",
    founder: "Mehul Nariyawala",
    location: "Mountain View, CA",
    state: "CA",
    lat: 37.3861,
    lng: -122.0839,
    fundingStage: "Series A",
    totalRaised: "$30M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/p/rational-optimist-awards-part-2",
    tags: ["robot vacuum", "AI", "consumer"]
  },
  {
    name: "Flexport",
    sector: "Consumer Tech",
    description: "Technology-driven freight forwarding and customs brokerage platform. Making global trade faster, more transparent, and accessible.",
    founder: "Ryan Peterson",
    location: "San Francisco, CA",
    state: "CA",
    lat: 37.7749,
    lng: -122.4194,
    fundingStage: "Late Stage",
    totalRaised: "$2.3B+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["logistics", "freight", "trade"]
  },
  {
    name: "Shinkei",
    sector: "Consumer Tech",
    description: "Robotics-enabled fish processing that improves quality and minimizes waste. $22M Series A from Founders Fund. Seremoni brand of ethically processed fish.",
    founder: "Saif Khawaja, Reed Ginsberg",
    location: "El Segundo, CA",
    state: "CA",
    lat: 33.9195,
    lng: -118.4168,
    fundingStage: "Series A",
    totalRaised: "$22M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["robotics", "fish processing", "food tech"]
  },
  {
    name: "Vital Lyfe",
    sector: "Consumer Tech",
    description: "Modern portable desalination and water filtration systems. Ex-SpaceX team. $24M Seed from General Catalyst and Interlagos. Affordable decentralized clean water.",
    founder: "Jonathan Criss, Andrew Harner",
    location: "Hawthorne, CA",
    state: "CA",
    lat: 33.9162,
    lng: -118.3524,
    fundingStage: "Seed",
    totalRaised: "$24M",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["desalination", "water", "filtration"]
  },
  {
    name: "Advanced Spade Company",
    sector: "Consumer Tech",
    description: "Detects magnetic fields underground for utility locating and undergrounding. Ex-Boring Company founder. Mapping underground in fire-stricken LA neighborhoods.",
    founder: "Daniel Kimminau",
    location: "Long Beach, CA",
    state: "CA",
    lat: 33.7715,
    lng: -118.1950,
    fundingStage: "Seed",
    totalRaised: "$5M+",
    valuation: "",
    rosLink: "https://rationaloptimistsociety.substack.com/",
    tags: ["utility locating", "underground", "mapping"]
  }
];
