/* ─── DARPA Performer Map ───
 * Renders three views on govradar.html:
 *   1. Performers (recipient list, sorted by total $ awarded)
 *   2. Programs (clustered by DARPA program tag)
 *   3. ROS-tracked only (frontier-tech matches from our COMPANIES roster)
 *
 * Data: data/darpa_programs_auto.js exposing window.DARPA_PROGRAMS_AUTO
 *   - Generated by scripts/fetch_darpa_programs.py from USAspending API
 *   - Every award has an awardId + verifyUrl back to USAspending
 *
 * Trust contract: every dollar amount and recipient is sourced from
 * USAspending.gov. No estimation, no inference. ROS company matches
 * are word-boundary string matches against our COMPANIES roster.
 */

(function () {
  'use strict';

  const esc = (typeof escapeHtml === 'function')
    ? escapeHtml
    : (s) => String(s == null ? '' : s).replace(/[&<>"']/g, (c) => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
      }[c]));

  let _data = null;
  let _activeView = 'performers';

  function fmtUSD(n) {
    if (!n || !isFinite(n)) return 'n/a';
    if (n >= 1e9) return '$' + (n / 1e9).toFixed(2) + 'B';
    if (n >= 1e6) return '$' + (n / 1e6).toFixed(1) + 'M';
    if (n >= 1e3) return '$' + (n / 1e3).toFixed(0) + 'K';
    return '$' + Math.round(n).toLocaleString();
  }

  function renderStats() {
    const wrap = document.getElementById('darpa-stats');
    if (!wrap || !_data) return;
    const rosCount = (_data.performers || []).filter(p => p.isRosCompany).length;
    wrap.innerHTML =
      '<div class="darpa-stat"><div class="darpa-stat-num">' + (_data.totalDollarsFormatted || fmtUSD(_data.totalDollars)) + '</div><div class="darpa-stat-lbl">Total Awarded (5yr)</div></div>' +
      '<div class="darpa-stat"><div class="darpa-stat-num">' + (_data.totalAwards || 0).toLocaleString() + '</div><div class="darpa-stat-lbl">Contracts</div></div>' +
      '<div class="darpa-stat"><div class="darpa-stat-num">' + (_data.performerCount || 0).toLocaleString() + '</div><div class="darpa-stat-lbl">Distinct Performers</div></div>' +
      '<div class="darpa-stat"><div class="darpa-stat-num" style="color:var(--accent);">' + rosCount + '</div><div class="darpa-stat-lbl">ROS-Tracked Frontier-Tech</div></div>' +
      '<div class="darpa-stat"><div class="darpa-stat-num">' + ((_data.programs || []).length) + '</div><div class="darpa-stat-lbl">Tagged Programs</div></div>';
  }

  function renderPerformers(rosOnly) {
    const content = document.getElementById('darpa-content');
    if (!content || !_data) return;
    let rows = (_data.performers || []).slice();
    if (rosOnly) rows = rows.filter(p => p.isRosCompany);
    if (rows.length === 0) {
      content.innerHTML = '<div class="darpa-meta-note">No performers match this filter.</div>';
      return;
    }
    rows = rows.slice(0, 50); // cap at 50 for the wide table

    const rowsHtml = rows.map((p, i) => {
      const programs = (p.programs || []).slice(0, 4).map(prog => '<span class="darpa-program-chip">' + esc(prog) + '</span>').join('');
      const sample = (p.topAwards && p.topAwards[0]) ? p.topAwards[0] : null;
      const verify = sample && sample.verifyUrl
        ? '<a href="' + esc(sample.verifyUrl) + '" target="_blank" rel="noopener" class="darpa-verify-link">USAspending →</a>'
        : '';
      const flag = p.isRosCompany ? '<span class="darpa-ros-badge">ROS</span>' : '';
      const profileLink = p.isRosCompany
        ? '<a href="company.html?name=' + encodeURIComponent(p.performer) + '" style="color:#fff; text-decoration:none;">' + esc(p.performer) + '</a>'
        : esc(p.performer);
      return '<tr>' +
        '<td style="font-family:Space Grotesk,monospace; color:rgba(239,68,68,0.7); font-weight:700;">#' + (i + 1) + '</td>' +
        '<td>' + profileLink + flag + '</td>' +
        '<td class="darpa-amount">' + esc(p.totalAwardedFormatted || fmtUSD(p.totalAwarded)) + '</td>' +
        '<td style="text-align:right; font-family:Space Grotesk,monospace;">' + (p.awardCount || 0) + '</td>' +
        '<td>' + (programs || '<span style="color:rgba(255,255,255,0.3); font-size:11px;">no program tag</span>') + '</td>' +
        '<td style="font-size:11px; color:rgba(255,255,255,0.5);">' + esc(p.lastDate || '') + '</td>' +
        '<td>' + verify + '</td>' +
      '</tr>';
    }).join('');

    content.innerHTML = '<div class="darpa-table-wrap"><table class="darpa-table">' +
      '<thead><tr><th style="width:48px;">#</th><th>Performer</th><th style="text-align:right;">Total $</th><th style="text-align:right;">Awards</th><th>Programs</th><th>Latest</th><th>Verify</th></tr></thead>' +
      '<tbody>' + rowsHtml + '</tbody></table></div>' +
      '<div class="darpa-meta-note">Showing top ' + rows.length + ' performer' + (rows.length !== 1 ? 's' : '') + ' by total $ awarded ' + (rosOnly ? '(ROS-tracked frontier-tech only)' : '') + '. Source: ' + esc(_data.source || 'USAspending') + ' · Last refresh: <code>' + esc(_data.generatedAt || '') + '</code></div>';
  }

  function renderPrograms() {
    const content = document.getElementById('darpa-content');
    if (!content || !_data) return;
    const rows = (_data.programs || []).slice(0, 30);
    if (rows.length === 0) {
      content.innerHTML = '<div class="darpa-meta-note">No tagged programs found in the lookback window.</div>';
      return;
    }
    const rowsHtml = rows.map((p, i) => {
      const ros = (p.rosPerformers || []).map(n =>
        '<a href="company.html?name=' + encodeURIComponent(n) + '" style="color:var(--accent); text-decoration:none;">' + esc(n) + '</a>'
      ).join(', ') || '<span style="color:rgba(255,255,255,0.3); font-size:11px;">none from ROS roster</span>';
      const top = (p.topAwards && p.topAwards[0]) ? p.topAwards[0] : null;
      const topRecipient = top ? esc(top.recipient) + ' (' + esc(top.amountFormatted || fmtUSD(top.amount)) + ')' : '—';
      const verify = top && top.verifyUrl
        ? '<a href="' + esc(top.verifyUrl) + '" target="_blank" rel="noopener" class="darpa-verify-link">Verify →</a>'
        : '';
      return '<tr>' +
        '<td style="font-family:Space Grotesk,monospace; color:rgba(239,68,68,0.7); font-weight:700;">#' + (i + 1) + '</td>' +
        '<td><span class="darpa-program-chip" style="font-size:12.5px; padding:3px 9px;">' + esc(p.program) + '</span></td>' +
        '<td class="darpa-amount">' + esc(p.totalAwardedFormatted || fmtUSD(p.totalAwarded)) + '</td>' +
        '<td style="text-align:right; font-family:Space Grotesk,monospace;">' + (p.performerCount || 0) + '</td>' +
        '<td style="font-size:12px;">' + topRecipient + '</td>' +
        '<td style="font-size:12px;">' + ros + '</td>' +
        '<td>' + verify + '</td>' +
      '</tr>';
    }).join('');
    content.innerHTML = '<div class="darpa-table-wrap"><table class="darpa-table">' +
      '<thead><tr><th style="width:48px;">#</th><th>Program</th><th style="text-align:right;">Total $</th><th style="text-align:right;">Performers</th><th>Largest Award</th><th>ROS-Tracked Performers</th><th>Verify</th></tr></thead>' +
      '<tbody>' + rowsHtml + '</tbody></table></div>' +
      '<div class="darpa-meta-note">Programs are inferred from award descriptions using a curated DARPA program-name dictionary. " HAWC", "BLACKJACK", "OPS-5G" etc. are well-known DARPA programs. Generic tags like "QUANTUM", "AUTONOMOUS" cluster awards by tech area when a specific program isn\'t named. Source: USAspending API.</div>';
  }

  function bindTabs() {
    const tabs = document.querySelectorAll('.darpa-tab');
    tabs.forEach(t => {
      t.addEventListener('click', () => {
        tabs.forEach(x => x.classList.remove('active'));
        t.classList.add('active');
        const view = t.getAttribute('data-view');
        _activeView = view;
        if (view === 'performers') renderPerformers(false);
        else if (view === 'programs') renderPrograms();
        else if (view === 'ros') renderPerformers(true);
      });
    });
  }

  function init() {
    if (typeof DARPA_PROGRAMS_AUTO === 'undefined') {
      console.warn('[DARPA] DARPA_PROGRAMS_AUTO not loaded');
      const content = document.getElementById('darpa-content');
      if (content) content.innerHTML = '<div class="darpa-meta-note">DARPA performer data is being rebuilt. Expected live: next sync cycle.</div>';
      return;
    }
    _data = DARPA_PROGRAMS_AUTO;
    renderStats();
    bindTabs();
    renderPerformers(false);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
