#!/usr/bin/env python3
"""
Add thesisCluster and techApproach fields to all companies in data.js.
Run from repo root: python3 scripts/add_thesis_fields.py
"""
import re
import json
import sys

# ─── THESIS CLUSTER DEFINITIONS ───
# Maps each cluster ID to its human-readable label
CLUSTER_LABELS = {
    "additive-manufacturing": "Additive Manufacturing & 3D Printing",
    "ai-autonomous-driving": "Autonomous Driving & Trucking AI",
    "ai-clinical-health": "AI for Clinical & Health Data",
    "ai-code-generation": "AI Code Generation & Software Engineering",
    "ai-computer-vision-sensing": "AI Computer Vision & Sensor Analytics",
    "ai-defense-intelligence": "AI for Defense & Intelligence Analysis",
    "ai-drug-discovery": "AI/ML-Driven Drug Discovery & Protein Design",
    "ai-foundation-models": "Foundation Model Development",
    "ai-generative-media": "Generative AI for Media",
    "ai-hardware-inference": "AI Inference Accelerator Chips & Novel Compute",
    "ai-materials-simulation": "AI for Materials Discovery & Simulation",
    "ai-mineral-exploration": "AI-Driven Mineral & Resource Exploration",
    "ai-robotics-embodied": "Embodied AI & Robot Foundation Models",
    "ai-saas-enterprise": "AI-Native Enterprise SaaS & Data Platforms",
    "ai-weather-earth": "AI for Weather & Earth Systems",
    "autonomy-counter-drone": "Counter-Drone & Drone Defense",
    "autonomy-delivery-logistics": "Autonomous Delivery Drones & Pods",
    "autonomy-drone-military": "Military Drone Platforms & Swarms",
    "autonomy-ground-vehicles": "Autonomous Ground Vehicles (Off-Road/Military)",
    "autonomy-maritime": "Autonomous Maritime & Underwater Vehicles",
    "battery-advanced-chemistry": "Advanced Battery Chemistry",
    "battery-infrastructure": "Battery Recycling, Inspection & Grid Integration",
    "biotech-cell-reprogramming": "Cellular Reprogramming & Longevity",
    "biotech-crispr-genomics": "CRISPR, Genomics & Embryo Screening",
    "biotech-lab-automation": "Automated Biomanufacturing & Lab Robotics",
    "biotech-novel-biology": "Novel Biology (Synthetic Bio, Xenotransplant, Cultivated)",
    "brain-computer-interface": "Brain-Computer Interfaces & Neural Prosthetics",
    "carbon-capture-dac": "Direct Air Capture",
    "carbon-capture-utilization": "Carbon Capture, Utilization & Biosequestration",
    "cement-green": "Zero-Carbon Cement & Concrete",
    "chiplet-packaging-foundry": "Advanced Chip Packaging & Foundry",
    "construction-modular": "Modular & Automated Construction",
    "consumer-hardware": "Consumer Hardware, Devices & EdTech",
    "data-center-infrastructure": "Data Center Power, Connectivity & Edge Compute",
    "defense-ew-rf-cyber": "Electronic Warfare, RF Sensing & Defense Cyber",
    "defense-munitions-energetics": "Precision Munitions & Energetics Manufacturing",
    "electrolysis-green-hydrogen": "Green Hydrogen & Electrolysis",
    "energy-storage-thermal-gravity": "Thermal, Gravity & Mechanical Energy Storage",
    "evtol-air-taxi": "eVTOL & Urban Air Mobility",
    "fusion-alternative": "Alternative Fusion (Z-Pinch, Pulsed, Projectile, Dipole)",
    "fusion-inertial-laser": "Inertial/Laser-Driven Fusion",
    "fusion-magnetic-confinement": "Magnetic Confinement Fusion (Tokamak & Stellarator)",
    "geothermal-next-gen": "Next-Generation Geothermal Energy",
    "green-steel-metals": "Green Steel & Electrochemical Metals",
    "humanoid-robotics": "Humanoid & Bipedal Robots",
    "inspection-quality-robots": "Industrial Inspection & Quality Robots",
    "logistics-supply-chain": "Logistics, Supply Chain & Freight Automation",
    "manufacturing-reshoring": "US Manufacturing Revival & Precision Machining",
    "maritime-electric-transport": "Electric & Alternative Maritime Transport",
    "medical-devices-surgical": "Medical Devices & Surgical Robotics",
    "nuclear-microreactor": "Nuclear Microreactors & Portable Fission",
    "nuclear-msr": "Molten Salt Reactors",
    "nuclear-services-fuel": "Nuclear Fuel Cycle, Waste & Services",
    "nuclear-smr-advanced": "Advanced Small Modular Reactors",
    "quantum-neutral-atom": "Neutral Atom Quantum Computing",
    "quantum-photonic": "Photonic Quantum Computing",
    "quantum-sensors-software": "Quantum Sensors, Control, Software & Alt Qubits",
    "quantum-superconducting": "Superconducting Quantum Computing",
    "quantum-trapped-ion": "Trapped-Ion Quantum Computing",
    "robotics-agriculture": "Agricultural Robotics",
    "robotics-cobots-warehouse": "Cobots, Warehouse Automation & RaaS",
    "robotics-construction-mining": "Construction & Mining Autonomy",
    "satellite-earth-observation": "Earth Observation & Remote Sensing Satellites",
    "semiconductor-advanced-materials": "Advanced Semiconductor Materials & Interconnects",
    "space-debris-servicing": "Space Debris Removal & In-Space Servicing",
    "space-ground-comms": "Space Communications, Ground Infra & Tracking",
    "space-habitats-manufacturing": "Space Stations & In-Space Manufacturing",
    "space-launch-large": "Large & Medium Launch Vehicles",
    "space-launch-small-intl": "Small Launch Vehicles (International)",
    "space-lunar-planetary": "Lunar, Planetary & Asteroid Systems",
    "space-propulsion-engines": "In-Space Propulsion & Rocket Engines",
    "space-satellites-buses": "Satellite Buses, Manufacturing & Rad-Hard Computing",
    "space-solar-power": "Space-Based Solar Power & Sunlight Redirection",
    "supersonic-hypersonic-transport": "Supersonic & Hypersonic Transport",
    "synfuels-solar": "Synthetic Fuels & Solar-to-Fuel",
    "transport-electric-vehicles": "Electric Vehicles & EV Infrastructure",
}

# ─── COMPANY → CLUSTER + TECH APPROACH MAPPING ───
# Each entry: "Company Name": ("cluster-id", "1-2 sentence tech approach")
COMPANY_DATA = {
    # === AI & Software ===
    "Physical Intelligence": ("ai-robotics-embodied", "Foundation models trained on diverse robot data enabling any robot to perform complex physical tasks through a universal AI brain"),
    "Waymo": ("ai-autonomous-driving", "Lidar + camera + radar sensor fusion with end-to-end ML driving stack, trained on billions of real-world miles"),
    "Figure AI": ("humanoid-robotics", "General-purpose humanoid robots combining LLM reasoning with learned motor control for warehouse and industrial tasks"),
    "Neuralink": ("brain-computer-interface", "Implantable 1,024-electrode brain-computer interface using custom ASIC for high-bandwidth neural signal processing"),
    "Field AI": ("ai-robotics-embodied", "Embodied AI foundation models enabling autonomous robot operation in unstructured industrial environments without pre-mapping"),
    "Nominal": ("ai-saas-enterprise", "Engineering observability platform for hardware testing and reliability, replacing spreadsheets with real-time test data analytics"),
    "Palantir": ("ai-saas-enterprise", "Ontology-based data integration platform mapping real-world entities and relationships for government and enterprise decision-making"),
    "Cognition": ("ai-code-generation", "Devin autonomous AI software engineer capable of end-to-end coding, debugging, and deployment with minimal human supervision"),
    "Applied Intuition": ("ai-autonomous-driving", "Simulation-first platform generating synthetic driving scenarios at scale for autonomous vehicle development and validation"),
    "Anthropic": ("ai-foundation-models", "Constitutional AI approach training large language models with built-in safety constraints through RLHF and interpretability research"),
    "Anysphere": ("ai-code-generation", "Cursor AI-powered code editor using frontier models for inline code generation, understanding, and refactoring in real-time"),
    "Air Space Intelligence": ("ai-weather-earth", "AI decision intelligence optimizing complex operations and logistics through real-time data synthesis and predictive modeling"),
    "Atmo": ("ai-weather-earth", "Physics-informed AI weather models delivering 50% more accurate forecasts than traditional numerical weather prediction"),
    "Beacon AI": ("ai-weather-earth", "AI copilot for commercial aviation providing real-time flight optimization, safety monitoring, and autonomous flight assistance"),
    "OpenAI": ("ai-foundation-models", "Frontier AI lab building GPT-series models through massive-scale pretraining and RLHF alignment for general intelligence"),
    "Mistral AI": ("ai-foundation-models", "European frontier AI lab building efficient open-weight and commercial LLMs competitive with GPT-4 at smaller model sizes"),
    "Groq": ("ai-hardware-inference", "Custom LPU (Language Processing Unit) silicon architecture delivering 10x inference speed through deterministic, sequential processing"),
    "Skild AI": ("ai-robotics-embodied", "Universal robot foundation model trained on diverse embodiments enabling zero-shot transfer of skills across different robot types"),
    "Crusoe Energy": ("data-center-infrastructure", "AI data centers powered by stranded natural gas and renewable energy, turning waste energy into compute capacity"),
    "ElevenLabs": ("ai-generative-media", "Neural voice synthesis using proprietary TTS models for realistic voice cloning, dubbing, and audio generation in 29 languages"),
    "Hippocratic AI": ("ai-clinical-health", "Safety-focused LLM specifically trained on medical data with built-in clinical guardrails for healthcare applications"),
    "Wayve": ("ai-autonomous-driving", "End-to-end learned autonomous driving using embodied intelligence rather than hand-coded rules, trained on London driving data"),
    "Hugging Face": ("ai-foundation-models", "Open-source ML platform hosting 500K+ models with standardized APIs, enabling democratic access to frontier AI research"),
    "Kyutai": ("ai-foundation-models", "French open-source AI research lab building real-time multimodal models with voice-native interaction capabilities"),
    "Gladia": ("ai-generative-media", "Enterprise speech AI providing real-time transcription, translation, and audio intelligence through optimized ASR pipelines"),
    "Dunia": ("ai-saas-enterprise", "Multi-agent AI systems for enterprise automation, orchestrating specialized AI agents for complex business workflows"),
    "Phospho": ("ai-generative-media", "AI observability platform monitoring, evaluating, and improving production LLM application quality through automated testing"),
    "Turbopuffer": ("data-center-infrastructure", "Serverless vector database architecture optimized for sub-millisecond similarity search at massive scale for AI-native applications"),
    "Attio": ("ai-saas-enterprise", "AI-native CRM automatically enriching and structuring relationship data using ML-driven entity resolution and signal detection"),
    "Day.ai": ("ai-saas-enterprise", "AI meeting intelligence capturing, summarizing, and acting on conversation data to automate follow-ups and relationship tracking"),
    "Ambient.ai": ("ai-computer-vision-sensing", "Computer vision platform for physical security using real-time video analytics to detect threats with near-zero false positives"),
    "Databricks": ("ai-saas-enterprise", "Lakehouse architecture unifying data warehousing and data lakes with native ML/AI training capabilities on Apache Spark"),
    "Hive AI": ("ai-computer-vision-sensing", "Pre-trained computer vision and NLP models via API for automated content moderation, visual search, and media analysis"),
    "Labelbox": ("ai-computer-vision-sensing", "Data factory platform combining human annotation, model-assisted labeling, and active learning for high-quality AI training data"),
    "Prepared": ("ai-computer-vision-sensing", "AI-powered 911 emergency dispatch using real-time speech analysis and situational awareness to improve response times"),
    "Sift": ("ai-saas-enterprise", "ML-based fraud detection using device fingerprinting, behavioral biometrics, and network analysis across payment and account flows"),
    "Surge AI": ("ai-computer-vision-sensing", "Specialized data annotation for RLHF and language data labeling using expert human evaluators for frontier model training"),
    "Cohere": ("ai-foundation-models", "Enterprise-focused LLMs with RAG-optimized architectures for business applications, multilingual support, and on-premise deployment"),
    "Ada": ("ai-saas-enterprise", "AI-driven customer support automation using LLMs fine-tuned on company-specific data to resolve inquiries across channels"),
    "Sakana AI": ("ai-drug-discovery", "Nature-inspired AI research building foundation models using evolutionary and swarm optimization rather than traditional training"),
    "Together AI": ("ai-foundation-models", "Open-source AI infrastructure providing optimized training, fine-tuning, and inference for open models at scale"),
    "Runway": ("ai-generative-media", "Generative AI for video creation using diffusion models for text-to-video, image-to-video, and cinematic visual effects"),
    "Humane": ("consumer-hardware", "AI-powered wearable device (AI Pin) using projection and voice as primary interfaces to replace smartphone-centric computing"),
    "Twelve Labs": ("ai-computer-vision-sensing", "Multimodal AI foundation models for video understanding enabling semantic search, classification, and generation from video content"),
    "Kolena": ("ai-computer-vision-sensing", "ML testing and validation platform enabling systematic evaluation of model performance across edge cases and data slices"),
    "Modal": ("data-center-infrastructure", "Serverless cloud infrastructure abstracting GPU provisioning and container orchestration for AI/ML workloads with pay-per-use"),

    # === Advanced Materials ===
    "Kyten Technologies": ("semiconductor-advanced-materials", "High-performance carbon nanotube manufacturing using proprietary CVD process for aerospace, defense, and semiconductor applications"),
    "Fairmat": ("semiconductor-advanced-materials", "AI-driven robotics for near-infinite recycling of carbon fiber composites, turning aerospace waste into reusable structural materials"),

    # === Biotech & Health ===
    "Altos Labs": ("biotech-cell-reprogramming", "Cell reprogramming using Yamanaka factors to reverse biological aging, backed by $3B to turn rejuvenation research into therapies"),
    "Retro Biosciences": ("biotech-cell-reprogramming", "Targeting three core aging mechanisms: toxic blood molecules, genetic errors, and cellular senescence through combined interventions"),
    "New Limit": ("biotech-cell-reprogramming", "Epigenetic reprogramming using safe transcription factor combinations to reverse age-related cellular decline without full dedifferentiation"),
    "Atom Bodies": ("brain-computer-interface", "AI-powered prosthetic arms with 26 degrees of finger freedom using LLMs to interpret neural signals for natural hand control"),
    "Mammoth Biosciences": ("biotech-crispr-genomics", "Next-gen CRISPR gene editing using novel Cas proteins for programmable diagnostics and therapeutics with improved precision"),
    "Nucleus Genomics": ("biotech-crispr-genomics", "Full genome screening platform offering affordable genomic sequencing with AI-driven risk interpretation for preventive medicine"),
    "Orchid": ("biotech-crispr-genomics", "Embryo screening using polygenic risk scores to help IVF parents select embryos with lower disease risk across multiple conditions"),
    "Herasight": ("biotech-crispr-genomics", "Polygenic embryo screening using whole-genome sequencing and AI analysis for IVF embryo selection with comprehensive trait coverage"),
    "Science Corporation": ("brain-computer-interface", "Brain-computer interfaces and organ preservation using advanced neural recording and optogenetic stimulation technologies"),
    "Andromeda Surgical": ("medical-devices-surgical", "Autonomous surgical robots using AI vision and machine learning to perform precise procedures with reduced human intervention"),
    "Recursion Pharmaceuticals": ("ai-drug-discovery", "AI-driven drug discovery at massive scale combining automated wet labs, ML models, and biological data to find new therapeutics"),
    "Insitro": ("ai-drug-discovery", "ML-driven drug discovery using large-scale cellular data, iPSC models, and machine learning to predict drug candidates in silico"),
    "Eikon Therapeutics": ("ai-drug-discovery", "Super-resolution microscopy tracking individual protein molecules in living cells to discover drugs based on real-time biology"),
    "Tempus AI": ("ai-clinical-health", "AI platform analyzing clinical and molecular data to personalize cancer treatment through genomic sequencing and ML-driven insights"),
    "Colossal Biosciences": ("biotech-novel-biology", "De-extinction using CRISPR gene editing to bring back woolly mammoth and Tasmanian tiger through elephant/marsupial genetic engineering"),
    "Medra": ("biotech-lab-automation", "Autonomous robotic systems that automate repetitive biological experiments 24/7 with ML-optimized experimental design"),
    "Abridge": ("ai-clinical-health", "NLP system that transcribes doctor-patient conversations into structured clinical notes integrated directly into EHR systems"),
    "Oxford Nanopore Technologies": ("biotech-crispr-genomics", "Nanopore-based DNA/RNA sequencing using protein pores to read genetic sequences in real-time on portable devices"),
    "DNA Script": ("biotech-crispr-genomics", "Enzymatic DNA synthesis using engineered enzymes instead of chemicals for rapid, on-demand production of custom DNA sequences"),
    "Neko Health": ("ai-clinical-health", "Full-body scanning using advanced hardware and AI diagnostics to detect diseases early through comprehensive preventive health screening"),
    "Solar Foods": ("biotech-novel-biology", "Producing protein from CO2, water, and electricity using hydrogen-oxidizing bacteria — food without agriculture or photosynthesis"),
    "Truemed": ("ai-clinical-health", "Platform enabling purchases of health products with pre-tax HSA/FSA dollars through physician-verified medical necessity"),
    "Lotus Health AI": ("ai-clinical-health", "AI-powered health platform using ML for personalized health insights, risk prediction, and preventive care recommendations"),
    "Multiply Labs": ("biotech-lab-automation", "Cloud-controlled robotic biomanufacturing automating cell and gene therapy production to solve the scalability bottleneck"),
    "Trilobio": ("biotech-lab-automation", "Fully automated robotic lab-in-a-box combining robotics, microfluidics, and AI for autonomous biological experimentation"),
    "eGenesis": ("biotech-novel-biology", "CRISPR-engineered pig organs for xenotransplantation, using 69+ gene edits to make pig kidneys compatible with human recipients"),
    "Vivodyne": ("biotech-novel-biology", "Lab-grown human organ models for pharmaceutical testing, replacing animal trials with physiologically accurate tissue systems"),
    "Cellares": ("biotech-lab-automation", "Automated cell therapy manufacturing platform scaling CAR-T production from weeks to days through end-to-end robotic processing"),
    "LabGenius": ("ai-drug-discovery", "ML-driven antibody discovery combining AI protein design with automated high-throughput screening in a closed-loop system"),
    "Mission Barns": ("biotech-novel-biology", "Cultivated animal fat produced through cell culture technology, creating real fat without animals for food applications"),
    "Zeta Surgical": ("medical-devices-surgical", "AI-powered surgical navigation using intraoperative imaging and real-time guidance for minimally invasive neurosurgery"),
    "Asimov": ("biotech-novel-biology", "Synthetic biology CAD tools for designing genetic circuits and cell lines with predictable behavior for biomanufacturing"),
    "Profluent": ("ai-drug-discovery", "De novo protein design using large language models trained on protein sequences to generate novel functional proteins"),

    # === Chips & Semiconductors ===
    "Cerebras": ("ai-hardware-inference", "Wafer-scale AI chip with 4+ trillion transistors on a single dinner-plate-sized die, eliminating memory bandwidth bottlenecks"),
    "Etched": ("ai-hardware-inference", "Transformer-specific ASIC with architecture burned into silicon, delivering 10x performance per watt vs. GPUs for inference"),
    "Extropic": ("ai-hardware-inference", "Thermodynamic computing using physical noise as computational resource, harnessing natural analog processes for generative AI"),
    "Lightmatter": ("data-center-infrastructure", "Photonic interconnects replacing copper with fiber-optic data pathways between chips, enabling 100x bandwidth at lower power"),
    "Substrate": ("semiconductor-advanced-materials", "X-ray lithography enabling sub-1nm chip patterning without EUV, using shorter wavelength light for more precise transistor printing"),
    "Lab 91": ("semiconductor-advanced-materials", "2D semiconductor using Molybdenum Disulfide (MoS2) instead of silicon for transistors, enabling continued Moore's Law scaling"),
    "Atom Computing": ("quantum-neutral-atom", "Neutral atom quantum computing trapping individual atoms in optical tweezers, demonstrated 1,000+ qubit arrays"),
    "Atomic Semi": ("chiplet-packaging-foundry", "Rapid-prototyping semiconductor fab reducing chip development from months to days for defense and specialty applications"),
    "Atomic Machines": ("semiconductor-advanced-materials", "Atomic-scale MEMS building programmable matter and nanoelectromechanical systems at the level of individual atoms"),
    "PsiQuantum": ("quantum-photonic", "Million-qubit photonic quantum computer using single-photon sources in standard silicon fabs for manufacturing scalability"),
    "Astera Labs": ("data-center-infrastructure", "Semiconductor connectivity solutions (PCIe/CXL retimers, smart cable modules) enabling coherent data center fabric at scale"),
    "Zettascale": ("ai-hardware-inference", "Energy-efficient AI chips designed for massive-scale compute with novel architecture optimized for transformer workloads"),
    "d-Matrix": ("ai-hardware-inference", "In-memory computing chiplets performing AI inference directly in SRAM, eliminating data movement bottleneck between memory and compute"),
    "Black Semiconductor": ("semiconductor-advanced-materials", "Graphene-based interconnects for next-gen chips, using 2D carbon materials to overcome copper wire resistance limits at small nodes"),
    "Wiliot": ("consumer-hardware", "Stamp-sized IoT sensor tags powered by harvesting ambient radio frequency energy, enabling battery-free intelligence on any product"),
    "Rapidus": ("chiplet-packaging-foundry", "Next-gen 2nm semiconductor foundry in Japan backed by $10B+ government investment to restore Japanese chip manufacturing leadership"),
    "Rebellions": ("ai-hardware-inference", "AI inference chips (ATOM, REBEL) designed for data center deployment with competitive performance-per-watt versus NVIDIA"),
    "Tenstorrent": ("ai-hardware-inference", "Open-source RISC-V AI processors with chiplet architecture, led by legendary architect Jim Keller, enabling customizable AI compute"),
    "Silicon Box": ("chiplet-packaging-foundry", "Advanced chiplet-based semiconductor packaging using fan-out wafer-level technology for heterogeneous chip integration"),

    # === Climate & Energy ===
    "Terraform Industries": ("synfuels-solar", "Modular synthetic natural gas from solar power and atmospheric CO2 using low-cost electrolysis and Sabatier methanation"),
    "Commonwealth Fusion Systems": ("fusion-magnetic-confinement", "Compact tokamak fusion using high-temperature superconducting (HTS) REBCO magnets enabling 20x stronger magnetic fields"),
    "Fervo Energy": ("geothermal-next-gen", "Enhanced geothermal using horizontal directional drilling borrowed from oil industry to access hot rock anywhere on Earth"),
    "Xcimer Energy": ("fusion-inertial-laser", "Massive excimer laser arrays for inertial confinement fusion, scaling NIF-style approach with cheaper, more efficient laser technology"),
    "Helion": ("fusion-magnetic-confinement", "Field-reversed configuration plasma fusion with direct electricity conversion bypassing steam turbines for 95% efficient power output"),
    "TAE Technologies": ("fusion-magnetic-confinement", "Field-reversed configuration using advanced proton-boron (p-B11) aneutronic fuel producing charged particles instead of neutrons"),
    "Mazama": ("geothermal-next-gen", "Supercritical geothermal drilling accessing 400+ degree rock for 10x energy density versus conventional geothermal wells"),
    "Quaise Energy": ("geothermal-next-gen", "Millimeter-wave drilling using gyrotron beams to vaporize rock to 20km depth, accessing unlimited geothermal heat anywhere"),
    "Captura": ("carbon-capture-utilization", "Ocean-based electrochemical carbon capture using seawater electrodialysis to remove CO2 while generating clean hydrogen"),
    "Base Power": ("battery-infrastructure", "Virtual power plants using distributed battery storage to provide grid services, turning home batteries into grid infrastructure"),
    "Karman Industries": ("electrolysis-green-hydrogen", "Industrial heat pumps using rocket turbomachinery engineering to replace fossil fuel burners in manufacturing processes"),
    "Claros": ("data-center-infrastructure", "Integrated power management technology for data centers using proprietary voltage regulation to maximize energy efficiency"),
    "Solugen": ("green-steel-metals", "Biomanufactured chemicals replacing petroleum feedstocks using engineered enzymes to produce hydrogen peroxide and organic acids"),
    "Exowatt": ("data-center-infrastructure", "Off-grid modular energy systems combining solar thermal storage with natural gas for AI data center power independence"),
    "Antora Energy": ("energy-storage-thermal-gravity", "Thermal energy storage in solid carbon blocks heated to 2400C by renewable electricity, delivering industrial heat on demand"),
    "Form Energy": ("battery-advanced-chemistry", "Iron-air batteries enabling 100-hour energy storage using reversible rusting of iron pellets for multi-day grid storage"),
    "Brimstone": ("cement-green", "Carbon-negative cement using calcium silicate rock instead of limestone, eliminating the 8% of global CO2 from cement production"),
    "Boston Metal": ("green-steel-metals", "Molten oxide electrolysis producing green steel using electricity instead of coal, eliminating carbon from steelmaking entirely"),
    "Avalanche Energy": ("fusion-alternative", "Compact modular micro-fusion using magnetized target approach in devices small enough to power individual buildings or vehicles"),
    "Bedrock Energy": ("geothermal-next-gen", "Next-gen geothermal HVAC using advanced underground heat exchange for building heating and cooling without fossil fuels"),
    "Arbor Energy": ("carbon-capture-utilization", "Biomass carbon removal converting agricultural waste into durable carbon materials while permanently sequestering CO2"),
    "Endurance Energy": ("geothermal-next-gen", "Seafloor geothermal energy extraction tapping vast thermal resources beneath the ocean floor for baseload clean power"),
    "Cape": ("defense-ew-rf-cyber", "Encrypted resilient mobile networks providing secure communications for defense and civilian use against interception"),
    "Aepnus Technology": ("green-steel-metals", "Electrochemical refining for critical minerals producing battery-grade lithium, nickel, and cobalt without traditional acid leaching"),
    "Heirloom Carbon": ("carbon-capture-dac", "Enhanced limestone mineralization for DAC using accelerated natural weathering to capture CO2 at low cost and permanent storage"),
    "Twelve": ("carbon-capture-utilization", "CO2 electrolysis converting captured carbon into chemicals, fuels, and materials using renewable electricity and proprietary catalysts"),
    "KoBold Metals": ("ai-mineral-exploration", "AI-driven mineral exploration using ML on geological, geophysical, and geochemical data to discover critical EV battery metals"),
    "Sublime Systems": ("cement-green", "Electrochemical cement manufacturing replacing 1450C kilns with room-temperature electrolysis for zero-carbon cement production"),
    "Redwood Materials": ("battery-infrastructure", "Closed-loop battery recycling recovering 95%+ of lithium, cobalt, and nickel from used batteries and manufacturing scrap"),
    "Natron Energy": ("battery-advanced-chemistry", "Sodium-ion batteries using Prussian Blue electrode chemistry for ultra-fast charging data center and EV infrastructure applications"),
    "EnerVenue": ("battery-advanced-chemistry", "Metal-hydrogen batteries adapted from NASA fuel cell technology for stationary storage with 30-year lifespan and zero degradation"),
    "Charm Industrial": ("carbon-capture-utilization", "Bio-oil carbon removal converting biomass into stable bio-oil injected deep underground for permanent geological carbon storage"),
    "Impulse Labs": ("battery-infrastructure", "Battery-integrated electric appliances delivering instant high power from built-in batteries to work on standard household circuits"),
    "Mariana Minerals": ("ai-mineral-exploration", "AI-powered mining operations combining software-enabled mine planning with autonomous extraction for critical mineral production"),
    "Gravitricity": ("energy-storage-thermal-gravity", "Gravity-based energy storage using heavy weights suspended in deep mine shafts, releasing energy by controlled descent"),
    "Sunfire": ("electrolysis-green-hydrogen", "High-temperature solid oxide electrolyzers achieving 90%+ efficiency for green hydrogen and syngas production at industrial scale"),
    "Verkor": ("battery-advanced-chemistry", "European battery gigafactory producing high-performance, low-carbon lithium-ion cells using dry electrode coating technology"),
    "H2 Green Steel": ("green-steel-metals", "Giga-scale green hydrogen steel plant replacing coal-based blast furnaces with hydrogen direct reduction in northern Sweden"),
    "Climeworks": ("carbon-capture-dac", "Modular direct air capture using solid sorbent filters and geothermal heat to permanently mineralize CO2 underground in Iceland"),
    "Synhelion": ("synfuels-solar", "Solar fuel production using concentrated sunlight at 1500C to thermochemically split CO2 and water into synthetic jet fuel"),
    "FREYR Battery": ("battery-advanced-chemistry", "Clean battery cell gigafactories using semi-solid electrode technology for simplified, lower-cost lithium-ion and sodium-ion cells"),
    "Skeleton Technologies": ("energy-storage-thermal-gravity", "Ultracapacitor energy storage using curved graphene electrodes for ultra-high power density in automotive and grid applications"),
    "Saule Technologies": ("consumer-hardware", "Perovskite solar cell technology printed on flexible substrates for building-integrated and portable photovoltaic applications"),
    "CarbonCure Technologies": ("carbon-capture-utilization", "CO2 mineralization injecting captured carbon into fresh concrete during mixing, permanently sequestering CO2 while strengthening concrete"),
    "SunDrive Solar": ("consumer-hardware", "Copper-replacing-silver solar cell metallization achieving world record efficiency while eliminating expensive silver from cell contacts"),
    "Pano AI": ("ai-computer-vision-sensing", "Panoramic camera and AI network for wildfire detection using thermal imaging, computer vision, and satellite data for real-time alerts"),
    "Floodbase": ("ai-computer-vision-sensing", "Satellite-based flood mapping using ML and SAR data to track flood extent in near-real-time for climate risk and disaster response"),
    "Liminal Insights": ("battery-infrastructure", "Ultrasound-based battery inspection using acoustic imaging to detect defects during manufacturing without destroying cells"),
    "WeaveGrid": ("battery-infrastructure", "ML-optimized EV-grid integration managing charging schedules to reduce grid stress while maximizing renewable energy utilization"),
    "Zanskar": ("ai-mineral-exploration", "AI platform for geothermal resource discovery using proprietary subsurface modeling to identify optimal drilling locations"),
    "Fortera": ("cement-green", "Zero-carbon cement using a reactive calcium carbonate process that captures CO2 during manufacturing rather than emitting it"),
    "LanzaTech": ("carbon-capture-utilization", "Gas fermentation using engineered bacteria to convert industrial CO2 emissions into ethanol, jet fuel, and chemical feedstocks"),
    "QuantumScape": ("battery-advanced-chemistry", "Solid-state lithium-metal batteries using ceramic solid electrolyte for 80% higher energy density and 15-minute fast charging"),
    "Mainspring Energy": ("energy-storage-thermal-gravity", "Linear generator technology converting any gaseous fuel into electricity through free-piston engine with 90% lower emissions"),
    "Watershed": ("ai-saas-enterprise", "Enterprise carbon accounting platform using proprietary emission factors and ML to measure, reduce, and report corporate carbon footprints"),
    "KLIR Sky": ("carbon-capture-dac", "Cryogenic carbon capture freezing smokestack CO2 to dry ice at -140C for permanent storage, avoiding chemical sorbent degradation"),
    "General Galactic": ("synfuels-solar", "Sustainable hydrocarbon synthesis producing fossil-free natural gas from renewable inputs for Earth and space applications"),
    "Steady Energy": ("nuclear-smr-advanced", "Compact factory-built SMRs designed for rapid deployment using proven pressurized water reactor technology in a modular format"),
    "CarbonCapture Inc.": ("carbon-capture-dac", "Modular direct air capture using mass-manufactured sorbent cartridges in a standardized, containerized system for rapid scaling"),
    "Graphyte": ("carbon-capture-utilization", "Biomass carbon storage converting plant waste into stable, compressed blocks that lock carbon away for thousands of years"),
    "Electric Hydrogen": ("electrolysis-green-hydrogen", "Industrial-scale PEM electrolyzers producing green hydrogen at fossil fuel cost parity for steel, ammonia, and fuel applications"),
    "Sage Geosystems": ("geothermal-next-gen", "Geopressured geothermal EarthStore system harvesting energy from pressurized underground formations while providing energy storage"),
    "Fourth Power": ("energy-storage-thermal-gravity", "Ultra-high-temperature thermal storage using 2400C liquid tin as heat transfer fluid in thermophotovoltaic generators"),
    "Cemvita Factory": ("carbon-capture-utilization", "Synthetic microbe engineering creating custom organisms that absorb CO2 and convert it into industrial chemicals and fuels"),
    "Solid Power": ("battery-advanced-chemistry", "Sulfide-based all-solid-state battery technology for EVs developed in partnership with Ford and BMW for safer, denser cells"),
    "CORE POWER": ("nuclear-smr-advanced", "Floating molten salt nuclear reactors for maritime propulsion and offshore power, decarbonizing the global shipping fleet"),
    "OpenStar": ("fusion-alternative", "Levitated dipole fusion using a magnetically suspended superconducting ring to confine plasma — the only company pursuing this approach"),

    # === Construction ===
    "Cuby Technologies": ("construction-modular", "Mobile micro-factories manufacturing homes from kits of parts using portable factory equipment for on-site construction"),
    "Cuby": ("construction-modular", "Mobile micro-factories manufacturing homes from kits of parts using portable factory equipment for on-site construction"),
    "Cover": ("construction-modular", "Factory-manufactured panel-based modular construction producing custom homes from precision-engineered components"),
    "Inversion Space": ("space-habitats-manufacturing", "Orbital warehouses and reentry capsules for space-based logistics, storing and delivering goods from orbit on demand"),
    "Cobod": ("additive-manufacturing", "World's leading 3D construction printer (BOD2) extruding concrete layer by layer to build structures in under 24 hours"),

    # === Consumer Tech ===
    "Alpha School": ("consumer-hardware", "AI-powered K-12 education with two-hour school days using personalized learning algorithms to accelerate student mastery"),
    "Matic Robotics": ("inspection-quality-robots", "Autonomous robot vacuum using AI computer vision mapping and navigation for efficient, intelligent home cleaning"),
    "Flexport": ("logistics-supply-chain", "Technology-driven freight forwarding using ML to optimize shipping routes, customs clearance, and supply chain visibility"),
    "Shinkei": ("robotics-agriculture", "Robotic fish processing using computer vision and precision robotics to automate ikejime technique for premium quality seafood"),
    "Vital Lyfe": ("consumer-hardware", "Modern portable desalination and water filtration using advanced membrane technology, designed by ex-SpaceX engineers"),
    "Advanced Spade Company": ("consumer-hardware", "Underground magnetic field detection for utility locating using novel magnetometer arrays to map buried infrastructure"),
    "Daylight Computer": ("consumer-hardware", "E-ink and LivePaper display computers designed around human circadian biology, reducing eye strain and improving focus"),
    "Synthesis": ("consumer-hardware", "AI-powered tutoring platform using game-based learning and personalized AI instruction for STEM education"),
    "Atom Limbs": ("brain-computer-interface", "Mind-controlled prosthetic arms using neural interfaces to enable natural, intuitive control of artificial limbs"),
    "Framework Computer": ("consumer-hardware", "Modular laptop designed for upgradeability and repair, letting users swap CPUs, screens, and ports to reduce e-waste"),
    "Whisper Aero": ("consumer-hardware", "Ultra-quiet electric propulsion using novel fan blade geometry to reduce noise by 20dB for drones and air vehicles"),
    "Osmo": ("consumer-hardware", "Digital olfaction using AI to encode, transmit, and reproduce scents — the first company to teleport a smell"),

    # === Defense & Security ===
    "Founder Tier": ("autonomy-drone-military", "Interoperable sensors and autonomous defense systems producing integrated battlefield awareness and response platforms"),
    "Shield AI": ("autonomy-drone-military", "Hivemind autonomous piloting software enabling drone swarms to fly, fight, and collaborate without GPS or communications"),
    "Epirus": ("autonomy-counter-drone", "High-power microwave directed energy weapon (Leonidas) disabling drone electronics at range with software-defined beam steering"),
    "Saronic": ("autonomy-maritime", "Autonomous surface vessels built at shipyard scale using vertical integration for rapid production of unmanned naval platforms"),
    "Neros": ("autonomy-drone-military", "High-volume FPV drone manufacturing producing 1,000+ combat drones monthly with optimized supply chains for rapid deployment"),
    "Chaos Industries": ("autonomy-counter-drone", "Coherent distributed networking radar using multiple nodes for counter-drone detection and tracking with no single point of failure"),
    "Castelion": ("defense-munitions-energetics", "Rapidly iterated hypersonic missile development using commercial aerospace practices to compress design cycles from years to months"),
    "CX2 Industries": ("defense-ew-rf-cyber", "Advanced RF sensing for battlefield situational awareness including Vadris drone detection and electronic warfare systems"),
    "Picogrid": ("defense-ew-rf-cyber", "Unified sensor-to-effector data integration platform connecting diverse battlefield sensors into a common operational picture"),
    "Skydio": ("autonomy-drone-military", "Autonomous AI-powered drones with obstacle avoidance and visual SLAM navigation — the only major US-made drone manufacturer"),
    "Allen Control Systems": ("defense-munitions-energetics", "Bullfrog autonomous gun turret achieving $10 cost-per-kill against drones using AI targeting and commodity ammunition"),
    "Mach Industries": ("defense-munitions-energetics", "Advanced propulsion and energetics for defense applications including solid rocket motors and munitions at startup speed"),
    "Andrenam": ("autonomy-maritime", "AI-powered distributed acoustic sensing for underwater and surface maritime security using networked hydrophone arrays"),
    "Vannevar Labs": ("ai-defense-intelligence", "Intelligence analysis and sensing platforms for DoD using NLP and ML to process classified and open-source data streams"),
    "Blue Water Autonomy": ("autonomy-maritime", "Mass-producible 100ft-class unmanned ships for naval endurance missions requiring minimal human oversight over weeks"),
    "Forterra": ("autonomy-ground-vehicles", "AI-powered autonomous ground vehicles for military logistics in GPS-denied, contested environments using perception AI"),
    "Auterion": ("autonomy-drone-military", "Open-source PX4 drone operating system providing interoperable autonomy software across allied defense drone platforms"),
    "Firehawk Aerospace": ("defense-munitions-energetics", "3D-printed hybrid rocket engines with customizable thrust profiles for missile and launch vehicle applications"),
    "Scale AI": ("ai-computer-vision-sensing", "AI data infrastructure providing high-quality labeled training data and evaluation tools for defense and enterprise ML models"),
    "Reveal Technology": ("ai-defense-intelligence", "Farsight AI-powered battlefield intelligence fusing multi-sensor data into real-time tactical situational awareness displays"),
    "Galvanick": ("defense-ew-rf-cyber", "Continuous OT/ICS cyber threat detection using ML to monitor industrial control systems in critical infrastructure"),
    "SkySafe": ("autonomy-counter-drone", "Counter-drone RF detection and mitigation using software-defined radio to detect, track, and neutralize rogue drones"),
    "Distributed Spectrum": ("defense-ew-rf-cyber", "AI-driven real-time RF sensing for electronic warfare, mapping the electromagnetic spectrum for signal detection and jamming"),
    "Aurelius Systems": ("autonomy-counter-drone", "Laser-based point-defense systems using directed energy for counter-drone and counter-missile intercept at speed of light"),
    "Darkhive": ("autonomy-drone-military", "Micro-drone swarm technology for indoor and GPS-denied operations using autonomous coordination in complex environments"),
    "Deterrence": ("defense-munitions-energetics", "Software-defined munitions manufacturing automating production at scale to rebuild American ammunition industrial capacity"),
    "Deepnight": ("defense-ew-rf-cyber", "Next-generation night vision and low-light imaging using advanced sensor technology for enhanced battlefield visibility"),
    "Zeromark": ("autonomy-counter-drone", "AI-powered auto-aiming counter-drone systems for infantry soldiers, enabling precise drone engagement with standard weapons"),
    "Rune Technologies": ("ai-defense-intelligence", "TyrOS military logistics AI operating system for asset tracking, personnel management, and operational planning"),
    "Swan": ("autonomy-drone-military", "Scalable autonomous products for defense and industrial applications through OEM partnerships and modular platforms"),
    "Biofire": ("defense-ew-rf-cyber", "Biometric smart firearm technology using fingerprint and facial recognition to prevent unauthorized weapon discharge"),
    "Firestorm Labs": ("autonomy-drone-military", "Mission-adaptable autonomous aerial vehicles at one-fifth traditional cost using modular payloads and AI autonomy"),
    "Helsing": ("ai-defense-intelligence", "European defense AI building ML-powered military decision systems for NATO allies with focus on data sovereignty"),
    "Saildrone": ("autonomy-maritime", "Autonomous wind and solar-powered ocean drones for persistent maritime ISR covering thousands of ocean square miles"),
    "Overland AI": ("autonomy-ground-vehicles", "Autonomous off-road ground vehicle technology for military resupply using terrain-adaptive perception and planning AI"),
    "Second Front": ("ai-defense-intelligence", "Game Warden software platform accelerating deployment of commercial software into DoD classified environments"),
    "Rebellion Defense": ("ai-defense-intelligence", "AI-powered decision support software for military planning using ML to process intelligence and accelerate OODA loops"),
    "Primer AI": ("ai-defense-intelligence", "NLP platform for intelligence analysis processing massive text volumes in 100+ languages for real-time threat assessment"),
    "True Anomaly": ("space-ground-comms", "Space domain awareness satellites and software for tracking, characterizing, and predicting orbital object behavior"),
    "Kodiak Robotics": ("ai-autonomous-driving", "Autonomous trucking technology for both commercial long-haul and military logistics using modular self-driving systems"),
    "Theseus": ("defense-ew-rf-cyber", "GPS-denied drone navigation using visual-inertial odometry and terrain matching for autonomous operations in contested airspace"),
    "Mara": ("autonomy-ground-vehicles", "Autonomous AI-powered robotic defense systems designed for perimeter security and asset protection in military contexts"),
    "Flock Safety": ("ai-computer-vision-sensing", "AI-powered license plate readers and surveillance camera network using edge ML for public safety and law enforcement"),
    "Icarus": ("autonomy-drone-military", "Next-generation autonomous aerial defense drones optimized for contested environments and rapid deployability"),
    "PILGRIM": ("medical-devices-surgical", "Battlefield biotech developing rapid-deployment medical interventions and trauma treatment technologies for military medicine"),
    "Quantum-Systems": ("autonomy-drone-military", "AI-powered autonomous eVTOL reconnaissance drones providing tactical ISR capabilities for military and security forces"),
    "Milrem Robotics": ("autonomy-ground-vehicles", "THeMIS unmanned ground vehicle — Europe's leading military ground robot for logistics, ISR, and combat support"),
    "Xtend": ("autonomy-drone-military", "Human-guided autonomous drone systems combining operator intuition with AI autonomy for complex defense missions"),
    "DroneShield": ("autonomy-counter-drone", "Multi-sensor counter-drone defense including RF detection, radar, acoustic sensing, and electronic jamming systems"),
    "Delian Alliance Industries": ("autonomy-maritime", "European autonomous maritime defense systems bridging allied navies with interoperable unmanned surface and undersea vehicles"),
    "Long Wall": ("defense-munitions-energetics", "Defense technology company building autonomous systems for military applications from Long Beach manufacturing base"),
    "SHIELD Technology Partners": ("ai-defense-intelligence", "Defense technology advisory and venture firm bridging Silicon Valley innovation with Department of Defense requirements"),
    "Aerodome": ("autonomy-drone-military", "Drone-as-first-responder providing fully automated drone systems for law enforcement and emergency response deployment"),
    "Modern Intelligence": ("ai-defense-intelligence", "Proprietary advances in information and complexity theory applied to defense intelligence analysis and decision systems"),
    "Swarm Aero": ("autonomy-drone-military", "Sensor mesh networking drone swarms with edge computing for coordinated ISR and electronic warfare missions"),
    "Kela": ("defense-ew-rf-cyber", "Defense integration platform providing modern technology solutions for Indo-Pacific allied military interoperability"),
    "goTenna": ("defense-ew-rf-cyber", "Mesh networking technology creating off-grid communication networks for military, first responder, and remote operations"),
    "FlyBy Robotics": ("autonomy-drone-military", "Low-cost drone swarms for military applications proving that quantity with AI coordination can overcome quality advantages"),
    "White Stork": ("autonomy-drone-military", "AI-powered autonomous drones for target identification and military strike missions using advanced computer vision and ML"),
    "Parry Labs": ("ai-defense-intelligence", "Digital systems integration modernizing legacy defense electronics with software-defined architectures and open standards"),
    "Fortem Technologies": ("autonomy-counter-drone", "DroneHunter autonomous interceptor using AI to detect, track, and physically capture rogue drones with net-based systems"),
    "Ares Industries": ("defense-munitions-energetics", "Next-gen precision-guided munitions designed for rapid production using modern manufacturing and simplified supply chains"),
    "Tenna Systems": ("defense-ew-rf-cyber", "Software platform transforming existing sensor data into real-time electromagnetic spectrum maps for situational awareness"),
    "Vatn Systems": ("autonomy-maritime", "Scalable autonomous underwater vehicles for US Navy undersea missions using modular, mass-producible AUV platforms"),
    "Hidden Level": ("defense-ew-rf-cyber", "Passive RF sensing detecting drones and aircraft by analyzing ambient radio signals without emitting detectable radar signatures"),

    # === Drones & Autonomous ===
    "Zipline": ("autonomy-delivery-logistics", "Autonomous delivery drones operating at national scale using fixed-wing aircraft with precision payload drop from altitude"),
    "Joby Aviation": ("evtol-air-taxi", "Electric vertical takeoff and landing air taxi using tilting propellers for quiet, zero-emission urban air mobility service"),
    "Rainmaker": ("autonomy-delivery-logistics", "Drone-enabled cloud seeding using autonomous aircraft to deploy silver iodide for targeted precipitation enhancement"),
    "Thoron": ("autonomy-drone-military", "US-manufactured drones positioned as domestic alternative to Chinese DJI for commercial, government, and defense applications"),
    "Airship Industries": ("autonomy-delivery-logistics", "Next-generation blimp and airship technology for heavy cargo transport, surveillance, and communications relay at low cost"),
    "Manna Aero": ("autonomy-delivery-logistics", "Drone delivery service operating 250,000+ commercial deliveries in Ireland using autonomous last-mile aerial delivery"),
    "Seneca Systems": ("autonomy-delivery-logistics", "Autonomous wildfire defense systems deploying drones and sensors for early detection, containment, and suppression coordination"),
    "Asylon Robotics": ("inspection-quality-robots", "Autonomous drone-in-a-box security systems providing continuous perimeter surveillance without human pilot operators"),
    "Aurora Innovation": ("ai-autonomous-driving", "Self-driving truck technology using the Aurora Driver autonomous system for commercial long-haul freight transportation"),
    "Nuro": ("autonomy-delivery-logistics", "Small autonomous delivery pods designed exclusively for goods delivery, eliminating the need for human-occupied vehicle design"),
    "Archer Aviation": ("evtol-air-taxi", "Midnight electric air taxi with 12 tilting propellers for urban air mobility, partnered with United Airlines for commercial service"),
    "Ridevalo": ("maritime-electric-transport", "Hydrofoiling electric water transport reimagining mass transit on waterways using foil-borne electric vessels"),
    "Flyby Robotics": ("autonomy-drone-military", "Autonomous drone systems for infrastructure inspection using AI-powered UAVs for automated visual assessment"),
    "Percepto": ("inspection-quality-robots", "Autonomous industrial drone-in-a-box robots for critical infrastructure inspection, monitoring, and security patrols"),
    "Tevel Aerobotics": ("robotics-agriculture", "Flying autonomous robots that use AI computer vision to identify and pick ripe fruit from trees without damaging crops"),
    "ideaForge": ("autonomy-drone-military", "Indian drone manufacturer for defense, homeland security, and industrial inspection with rugged, high-altitude capable platforms"),
    "Tekever": ("autonomy-drone-military", "Portuguese drone-as-a-service providing long-range unmanned ISR for defense, maritime patrol, and border surveillance"),
    "Dronamics": ("autonomy-delivery-logistics", "World's first cargo drone airline operating large fixed-wing drones for middle-mile logistics at one-tenth of air freight cost"),
    "Rhoman Aerospace": ("autonomy-drone-military", "Advanced autonomous aerial systems for defense and commercial applications using next-gen avionics and propulsion"),
    "AirMap": ("space-ground-comms", "Leading airspace management platform providing real-time drone traffic data, flight planning, and regulatory compliance"),
    "DroneForge": ("autonomy-drone-military", "AI-powered hardware platform and SDK transforming commercial drones into defense-capable autonomous systems"),
    "Rain Industries": ("autonomy-delivery-logistics", "Autonomous drones prepositioned in wildfire-prone areas for immediate aerial suppression response at scale"),

    # === Infrastructure & Logistics ===
    "Amperon": ("ai-saas-enterprise", "AI-powered energy grid forecasting using ML to predict electricity demand, generation, and pricing in real-time"),
    "Ample": ("battery-infrastructure", "Modular battery swapping for EVs replacing entire battery packs in under 5 minutes using standardized swappable modules"),
    "Blumen Systems": ("logistics-supply-chain", "Digital infrastructure development platform automating permitting, project management, and construction coordination"),
    "Durin": ("robotics-construction-mining", "Automated drill rigs for infrastructure and mining bringing autonomous precision drilling to reduce cost and improve safety"),
    "Elodin": ("evtol-air-taxi", "Flight software development platform accelerating certification and deployment of autonomous aircraft software systems"),
    "Bronco AI": ("logistics-supply-chain", "AI-powered supply chain automation for defense logistics optimizing procurement, inventory, and distribution workflows"),
    "Fortastra": ("logistics-supply-chain", "Next-generation infrastructure technology for resilient supply chains and critical infrastructure development"),
    "Earth AI": ("ai-mineral-exploration", "AI-powered mineral exploration using ML on geological data to discover critical metals with 10x better drill targeting"),
    "Watoga Tech": ("robotics-construction-mining", "Autonomous mining technology for safer, more efficient extraction of critical minerals using robotic systems"),
    "Wardstone": ("logistics-supply-chain", "Advanced infrastructure security and resilience technology protecting critical systems from physical and cyber threats"),
    "Teralta": ("electrolysis-green-hydrogen", "Hydrogen logistics and distribution infrastructure helping industrial buyers access green hydrogen when and where needed"),
    "GenMat": ("ai-materials-simulation", "AI system for atomic-level physics simulation discovering new materials and predicting their properties computationally"),
    "AiDash": ("ai-computer-vision-sensing", "Satellite imagery and AI platform helping utilities manage vegetation, assess climate risk, and optimize infrastructure"),

    # === Medical Devices ===
    "Cresilon": ("medical-devices-surgical", "Traumagel hemostatic gel using algae and fungi-based biopolymers to stop moderate to severe bleeding within seconds"),

    # === Nuclear Energy ===
    "Valar Atomics": ("nuclear-microreactor", "First startup to split the atom with its own reactor core, building gas-cooled microreactors for distributed power generation"),
    "Radiant": ("nuclear-microreactor", "Portable 1.2MW nuclear microreactors for off-grid and austere environments using helium-cooled TRISO fuel technology"),
    "Aalo Atomics": ("nuclear-microreactor", "Pragmatic microreactor design using existing fuel types and supply chains to accelerate deployment without novel fuel development"),
    "Antares": ("nuclear-microreactor", "Kilowatt-scale micro-fission reactors using heat pipe technology for defense and space power in remote locations"),
    "General Matter": ("nuclear-services-fuel", "Rebuilding American uranium enrichment capacity using centrifuge technology for HALEU fuel production for advanced reactors"),
    "Kairos Power": ("nuclear-msr", "Fluoride salt-cooled high-temperature reactor using TRISO fuel pebbles in molten fluoride salt for intrinsically safe operation"),
    "X-Energy": ("nuclear-smr-advanced", "Xe-100 pebble bed HTGR producing 80MW with TRISO fuel, modular design for AI data centers with Amazon partnership"),
    "Oklo": ("nuclear-microreactor", "Aurora fast fission microreactor and nuclear campus concept with waste-to-fuel recycling and Meta/Equinix data center partnerships"),
    "Last Energy": ("nuclear-microreactor", "Standardized microreactors deployed in containerized format for rapid installation with power purchase agreements"),
    "Deep Fission": ("nuclear-microreactor", "Underground microreactors deployed in one-mile-deep boreholes using natural geology as containment and shielding"),
    "TerraPower": ("nuclear-smr-advanced", "Natrium sodium-cooled fast reactor with integrated molten salt energy storage for load-following grid applications"),
    "Standard Nuclear": ("nuclear-services-fuel", "Standardized advanced reactor deployment using proven designs and streamlined licensing for rapid nuclear buildout"),
    "The Nuclear Company": ("nuclear-services-fuel", "Proven AP1000 reactor deployment philosophy building on existing certified designs rather than inventing new reactor concepts"),
    "Exodys Energy": ("nuclear-msr", "Molten salt fast reactor technology for recycling nuclear waste into fuel, turning liability into clean energy resource"),
    "NuScale Power": ("nuclear-smr-advanced", "VOYGR light water SMR — first SMR design to receive NRC certification, scaling proven PWR technology to smaller modules"),
    "Zap Energy": ("fusion-alternative", "Sheared-flow-stabilized Z-pinch fusion requiring no expensive superconducting magnets or lasers for simpler plasma containment"),
    "General Fusion": ("fusion-alternative", "Magnetized target fusion using mechanical compression with liquid metal pistons to squeeze plasma to fusion conditions"),
    "Type One Energy": ("fusion-magnetic-confinement", "Optimized stellarator fusion using advanced 3D-printed HTS magnets and AI-designed plasma geometry for steady-state operation"),
    "Focused Energy": ("fusion-inertial-laser", "Laser-driven inertial fusion energy building on NIF ignition breakthrough with improved target physics and laser efficiency"),
    "Nano Nuclear Energy": ("nuclear-microreactor", "Ultra-small portable nuclear reactors (ZEUS and ODIN) for remote power and nuclear fuel transportation services"),
    "Pacific Fusion": ("fusion-inertial-laser", "Next-gen inertial confinement fusion for commercial power using massive pulsed power and advanced target fabrication"),
    "Fuse Energy": ("fusion-alternative", "Pulsed power devices for nuclear effects testing — first fusion company to sell a product generating fusion revenue"),
    "Tokamak Energy": ("fusion-magnetic-confinement", "Compact spherical tokamak fusion using HTS magnets in a smaller, more efficient magnetic confinement geometry"),
    "First Light Fusion": ("fusion-alternative", "Projectile fusion firing hypervelocity projectiles at fuel targets to achieve fusion through extreme kinetic compression"),
    "Newcleo": ("nuclear-smr-advanced", "Lead-cooled fast reactor using MOX fuel from reprocessed spent nuclear fuel, turning waste stockpiles into clean energy"),
    "Proxima Fusion": ("fusion-magnetic-confinement", "Quasi-isodynamic stellarator design using AI optimization and HTS magnets, spun out from Max Planck Institute"),
    "Marvel Fusion": ("fusion-inertial-laser", "Laser-driven fusion using novel silicon nanostructured fuel targets to achieve higher energy gain than traditional ICF pellets"),
    "Naarea": ("nuclear-msr", "Molten salt microreactor (XAMR) for decentralized energy producing heat and electricity from thorium-based fuel"),
    "Renaissance Fusion": ("fusion-magnetic-confinement", "HTS magnet development and stellarator fusion using novel continuous coil winding for simplified stellarator construction"),
    "Seaborg Technologies": ("nuclear-msr", "Compact molten salt reactors deployed on floating barges for scalable, portable nuclear power in maritime settings"),
    "Copenhagen Atomics": ("nuclear-msr", "Modular thorium molten salt reactors in shipping container form factor for mass production and global deployment"),
    "Kyoto Fusioneering": ("fusion-magnetic-confinement", "Fusion plant engineering developing heat extraction, tritium breeding, and power conversion components for fusion reactors"),
    "Terrestrial Energy": ("nuclear-smr-advanced", "Integral Molten Salt Reactor (IMSR) combining fuel and coolant in a single salt for simplified reactor design and inherent safety"),
    "Deep Isolation": ("nuclear-services-fuel", "Horizontal directional drilling for deep geological nuclear waste disposal using oil industry drilling technology"),
    "Deep Atomic": ("nuclear-microreactor", "Next-generation reactor technology in development from Zurich, applying Swiss precision engineering to nuclear energy"),
    "ARC Clean Technology": ("nuclear-smr-advanced", "ARC-100 small modular reactor generating 100MW of clean electricity using proven sodium-cooled fast reactor technology"),
    "Hexium": ("nuclear-services-fuel", "Atomic Vapor Laser Isotope Separation (AVLIS) for lithium isotope enrichment critical for fusion reactor tritium breeding"),

    # === Ocean & Maritime ===
    "Bedrock Ocean": ("autonomy-maritime", "Autonomous underwater vehicles using advanced sonar for high-resolution seafloor mapping — building the Google Maps of the ocean"),
    "Amidon Heavy Industries": ("autonomy-maritime", "Autonomous underwater vehicles for defense and commercial applications with emphasis on mass-producible AUV platforms"),
    "Clippership": ("maritime-electric-transport", "Autonomous wind-powered cargo vessels using modern wing sail technology for zero-emission trans-oceanic freight shipping"),
    "NetworkOcean": ("data-center-infrastructure", "Underwater data centers leveraging deep ocean cooling for naturally efficient, sustainable computing infrastructure"),
    "Thalassa Robotics": ("autonomy-maritime", "Autonomous underwater robots for ocean exploration, inspection, and data collection in extreme deep-sea environments"),
    "Running Tide": ("carbon-capture-utilization", "Ocean-based carbon removal using kelp cultivation and alkalinity enhancement to sequester CO2 in deep ocean biomass"),
    "Orbital Marine Power": ("maritime-electric-transport", "World's most powerful tidal turbine (O2) generating clean electricity from predictable ocean tidal currents"),

    # === Quantum & Computing ===
    "Q-CTRL": ("quantum-sensors-software", "Quantum infrastructure software using optimal control theory to suppress hardware errors and extend qubit coherence times"),
    "Infleqtion": ("quantum-sensors-software", "Atom-based quantum sensors including atomic clocks 100x more precise than GPS and quantum RF receivers for defense"),
    "Rain AI": ("ai-hardware-inference", "Brain-inspired neuromorphic processing units (NPUs) for energy-efficient AI inference mimicking biological neural computation"),

    # === Quantum Computing ===
    "Conductor Quantum": ("quantum-sensors-software", "Silicon-based quantum computing making qubits on standard CMOS chips for compatibility with existing semiconductor manufacturing"),
    "IonQ": ("quantum-trapped-ion", "Trapped-ion quantum computing using individual ytterbium atoms suspended in electromagnetic fields for high-fidelity gate operations"),
    "Rigetti Computing": ("quantum-superconducting", "Full-stack superconducting quantum computing with cloud access via Rigetti Quantum Cloud Services and hybrid classical-quantum workflows"),
    "QuEra Computing": ("quantum-neutral-atom", "Neutral-atom quantum computer using programmable arrays of Rydberg atoms for analog and digital quantum computation"),
    "Oxford Quantum Circuits": ("quantum-superconducting", "Proprietary 3D Coaxmon superconducting qubit architecture providing better coherence through coaxial cavity coupling design"),
    "planqc": ("quantum-neutral-atom", "Neutral-atom quantum computing using optical lattices to trap atoms in ordered crystal-like arrays for scalable qubit control"),
    "Pasqal": ("quantum-neutral-atom", "Neutral-atom quantum processors using Nobel Prize-winning optical tweezer technology for programmable, scalable quantum systems"),
    "Alice & Bob": ("quantum-superconducting", "Cat qubit quantum computers that natively suppress bit-flip errors through quantum error correction built into hardware design"),
    "IQM Quantum Computers": ("quantum-superconducting", "Co-designed superconducting quantum computers optimized for specific applications like material simulation and optimization"),
    "QuantWare": ("quantum-superconducting", "Off-the-shelf superconducting quantum processors democratizing quantum hardware access through standardized QPU sales"),
    "Quantum Machines": ("quantum-sensors-software", "OPX+ quantum control hardware and operating system managing qubits with classical-quantum real-time feedback loops"),
    "Xanadu Quantum Technologies": ("quantum-photonic", "Photonic quantum computing using squeezed light states and Borealis processor, plus open-source PennyLane quantum ML framework"),
    "Quantum Brilliance": ("quantum-sensors-software", "Room-temperature quantum computing using synthetic diamond nitrogen-vacancy centers for portable quantum accelerators"),
    "D-Wave Quantum": ("quantum-sensors-software", "Quantum annealing using 5,000+ qubit Advantage processor for combinatorial optimization problems in logistics, materials, and finance"),
    "Photonic Inc": ("quantum-photonic", "Distributed quantum computing using silicon spin qubits connected via photonic links for modular, networked quantum architectures"),
    "Nord Quantique": ("quantum-superconducting", "Hardware-efficient quantum error correction using bosonic qubit encoding to achieve logical qubit performance without massive overhead"),
    "Quantinuum": ("quantum-trapped-ion", "Integrated trapped-ion quantum computing combining Honeywell precision engineering with Cambridge Quantum algorithms in H-Series processors"),
    "Qilimanjaro": ("quantum-superconducting", "Coherent analog superconducting quantum computers using fluxonium qubits for reduced error rates and improved gate fidelity"),
    "QuiX Quantum": ("quantum-photonic", "Commercial photonic quantum computers using proprietary TriPleX silicon nitride waveguide platform for room-temperature operation"),
    "SemiQon": ("quantum-sensors-software", "Cryogenic CMOS transistors consuming 0.1% of room-temperature power for quantum computing control electronics at millikelvin temperatures"),
    "Archer Materials": ("quantum-sensors-software", "Room-temperature carbon-based 12CQ qubit chip using single-atom spin properties in carbon lattices on standard silicon wafers"),

    # === Robotics & Manufacturing ===
    "Hadrian": ("manufacturing-reshoring", "Software-defined automated factories producing high-precision CNC machined parts for aerospace and defense with 10x faster turnaround"),
    "Machina Labs": ("manufacturing-reshoring", "Giant robotic arms performing AI-controlled metal forming, replacing expensive dies with flexible roboforming for rapid prototyping"),
    "DIRAC": ("manufacturing-reshoring", "Anti-software software generating optimized assembly instructions for industrial manufacturing from 3D models automatically"),
    "Formic": ("robotics-cobots-warehouse", "Robots-as-a-service making industrial automation accessible to SMEs through zero-upfront-cost robotic cell leasing"),
    "Rangeview": ("manufacturing-reshoring", "Automated foundry using robotics and materials science for investment casting of complex metal components at startup speed"),
    "Senra Systems": ("manufacturing-reshoring", "Software-defined wire harness manufacturing using robotic automation to produce complex wiring for aerospace and defense"),
    "Salient Motion": ("manufacturing-reshoring", "Critical actuation and motion control components for aviation and defense using precision-engineered electromechanical systems"),
    "Divergent": ("additive-manufacturing", "End-to-end additive manufacturing platform producing topology-optimized automotive and aerospace structures via metal 3D printing"),
    "Amca": ("manufacturing-reshoring", "Acquiring and modernizing legacy aerospace component suppliers through technology upgrades and operational improvements"),
    "Agility Robotics": ("humanoid-robotics", "Digit bipedal robot designed for warehouse logistics, first humanoid deployed commercially for repetitive material handling tasks"),
    "Apptronik": ("humanoid-robotics", "Apollo general-purpose humanoid robot for manufacturing and logistics using modular actuators and whole-body AI control"),
    "1X Technologies": ("humanoid-robotics", "NEO humanoid robot for home and commercial use, backed by OpenAI, using learned behaviors from simulation and teleoperation"),
    "Bright Machines": ("manufacturing-reshoring", "Software-defined manufacturing bringing AI intelligence to factory robot cells through automated vision inspection and assembly"),
    "Atomic Industries": ("manufacturing-reshoring", "AI-powered tool and die manufacturing modernizing the most critical bottleneck in American industrial production"),
    "Re:Build Manufacturing": ("manufacturing-reshoring", "Vertically integrated American manufacturing revival combining AI, automation, and reshoring of critical production capabilities"),
    "AMP Robotics": ("robotics-cobots-warehouse", "AI-powered recycling robots using computer vision to sort waste materials at superhuman speed and accuracy for circular economy"),
    "Diode": ("additive-manufacturing", "AI-automated circuit board design reducing PCB development time from weeks to hours through generative layout optimization"),
    "Quilter": ("additive-manufacturing", "Fully automated PCB layout using AI constraint satisfaction to produce optimal circuit board designs without human engineers"),
    "Covariant": ("robotics-cobots-warehouse", "RFM-1 robotic foundation model enabling AI-powered picking and sorting with generalized object manipulation in warehouses"),
    "Gecko Robotics": ("inspection-quality-robots", "Wall-climbing inspection robots using magnetic adhesion and AI to assess infrastructure health in tanks, boilers, and vessels"),
    "Terranova": ("robotics-construction-mining", "Planetary-scale autonomous robotics for infrastructure development and environmental applications in extreme environments"),
    "Electric Sheep": ("robotics-construction-mining", "Autonomous lawn care robots using AI navigation for commercial landscaping, replacing gas-powered equipment with electric autonomy"),
    "Carbon Robotics": ("robotics-agriculture", "LaserWeeder using computer vision and high-power lasers to eliminate weeds at 2 acres per hour without chemicals"),
    "Terran Robotics": ("construction-modular", "Autonomous construction robots operating in unstructured environments for automated building assembly and earth moving"),
    "NEURA Robotics": ("humanoid-robotics", "Cognitive robots that perceive and interact with environments using proprietary tactile, vision, and voice AI sensors"),
    "Exotec": ("robotics-cobots-warehouse", "Skypod warehouse robotics where robots climb storage racks vertically to retrieve items, maximizing vertical space utilization"),
    "ANYbotics": ("inspection-quality-robots", "ANYmal quadruped robot for autonomous industrial inspection in hazardous environments using dynamic legged locomotion"),
    "GITAI": ("space-habitats-manufacturing", "Space robotics building autonomous robots for in-space servicing, assembly, and manufacturing on space stations and satellites"),
    "Mujin": ("robotics-cobots-warehouse", "Real-time AI motion planning enabling fully autonomous warehouse operations with zero-teach robot programming"),
    "Rainbow Robotics": ("humanoid-robotics", "Collaborative and humanoid robots from KAIST HUBO lineage, partnered with Hyundai for next-gen manufacturing automation"),
    "Solinftec": ("robotics-agriculture", "Autonomous agricultural robots and AI farm machinery for large-scale precision farming in tropical and subtropical conditions"),
    "Neura Robotics": ("humanoid-robotics", "German cognitive robotics building MAiRA and 4NE-1 humanoid robots with multimodal AI perception for flexible manufacturing"),
    "Monumental": ("construction-modular", "Robotic bricklaying machines that autonomously lay bricks for wall construction using computer vision and precision placement"),
    "RobCo": ("robotics-cobots-warehouse", "Modular industrial robotics making automation accessible to SMEs through configurable, easy-to-deploy robotic systems"),
    "Grain Weevil": ("robotics-agriculture", "Autonomous grain bin management robot that monitors temperature, moisture, and quality while leveling stored grain automatically"),
    "Naïo Technologies": ("robotics-agriculture", "Autonomous weeding and crop care robots for organic and conventional farming using mechanical weed removal without herbicides"),
    "Prusa Research": ("additive-manufacturing", "Open-source 3D printer manufacturer building the most popular FDM printers through community-driven hardware and software development"),
    "Roboton": ("robotics-cobots-warehouse", "Czech robotics developing advanced industrial robotic systems for manufacturing automation and quality inspection"),
    "Bedrock Robotics": ("robotics-construction-mining", "Retrofitting existing excavators and bulldozers with autonomous control systems for precision earthwork and grading"),
    "GrayMatter Robotics": ("robotics-cobots-warehouse", "Physics-informed AI for robotic surface finishing, automating sanding, polishing, and painting with adaptive force control"),
    "RIOS Intelligent Machines": ("robotics-cobots-warehouse", "AI-powered end-to-end robotic workcells for factory, warehouse, and supply chain automation using dexterous manipulation"),
    "Orbital Composites": ("additive-manufacturing", "Robotic 3D printing of large carbon fiber composite structures for aerospace and industrial applications using continuous fiber"),
    "SafeAI": ("robotics-construction-mining", "Aftermarket autonomy for construction and mining heavy equipment using bolt-on sensors and AI for existing machines"),
    "Collaborative Robotics": ("robotics-cobots-warehouse", "Proxie mobile manipulator cobot combining navigation with manipulation for versatile, safe human-robot collaboration"),
    "Orangewood Labs": ("robotics-cobots-warehouse", "Affordable AI-powered collaborative robotic arms for small businesses, democratizing industrial automation with sub-$10K systems"),
    "Built Robotics": ("robotics-construction-mining", "Autonomous AI systems retrofitting construction equipment with sensors and software for automated earthwork operations"),
    "Chef Robotics": ("robotics-cobots-warehouse", "AI-powered robotic food assembly automating plating and portion control in commercial kitchens using vision-guided manipulation"),
    "Dexterity": ("logistics-supply-chain", "AI-powered robotic picking and packing for logistics using learned dexterity to handle diverse products in fulfillment centers"),
    "Farm-ng": ("robotics-agriculture", "Modular autonomous farm robots with open architecture allowing farmers to customize capabilities for diverse agricultural tasks"),
    "Locus Robotics": ("robotics-cobots-warehouse", "Warehouse AMRs that collaborate with human pickers to increase fulfillment productivity 2-3x through optimized path planning"),
    "Lumafield": ("inspection-quality-robots", "Industrial CT scanning providing accessible computed tomography for non-destructive inspection of manufactured components"),
    "Osaro": ("robotics-cobots-warehouse", "Deep reinforcement learning for robotic picking in warehouses, enabling AI-powered handling of diverse, unseen objects"),
    "Outrider": ("logistics-supply-chain", "Autonomous electric yard trucks for distribution center logistics, automating the most repetitive outdoor freight operations"),
    "Rapid Robotics": ("robotics-cobots-warehouse", "Risk-free robotic palletizing solutions using pre-configured robotic cells for rapid deployment in manufacturing and logistics"),
    "Sanctuary AI": ("humanoid-robotics", "Phoenix humanoid robot with Carbon AI control system pursuing artificial general intelligence through embodied learning"),
    "Kinova Robotics": ("robotics-cobots-warehouse", "Lightweight robotic arms for medical, assistive, and research applications with focus on accessibility and human interaction"),
    "Dusty Robotics": ("construction-modular", "Autonomous robots printing precise building layouts directly onto construction floors using robotic total station technology"),
    "Vayu Robotics": ("autonomy-delivery-logistics", "Autonomous last-mile delivery robots using AI perception for sidewalk navigation and package delivery in diverse environments"),
    "Ulysses Robotics": ("autonomy-maritime", "Autonomous underwater robotic systems for ocean exploration, data collection, and subsea industrial operations"),
    "Wandelbots": ("robotics-cobots-warehouse", "No-code NOVA platform enabling non-programmers to teach industrial robots tasks by demonstration rather than coding"),

    # === Semiconductors ===
    "AlixLabs": ("semiconductor-advanced-materials", "Atomic Layer Processing (APS) technology achieving sub-10nm patterning without EUV lithography using selective atomic-scale etching"),
    "DEEPX": ("ai-hardware-inference", "Edge AI chips designed by Apple A-series architect, delivering high-performance neural inference at ultra-low power for edge devices"),

    # === Space & Aerospace ===
    "SpaceX": ("space-launch-large", "Falcon 9 reusable orbital launch vehicle with 165 launches in 2025, plus Starship super heavy-lift vehicle for Mars colonization"),
    "Rocket Lab": ("space-launch-large", "Electron small launch vehicle plus Neutron medium-lift, only company besides SpaceX with proven reusable orbital launch capability"),
    "Apex Space": ("space-satellites-buses", "Standardized, configurable satellite bus platform — the Foxconn of space — enabling rapid, low-cost satellite manufacturing"),
    "Varda Space Industries": ("space-habitats-manufacturing", "Microgravity pharmaceutical manufacturing on autonomous capsules that process drugs in orbit and return them via reentry"),
    "AstroForge": ("space-lunar-planetary", "Asteroid mining targeting platinum-group metals using autonomous spacecraft for resource extraction in deep space"),
    "Reflect Orbital": ("space-solar-power", "Constellation of lightweight reflective satellites redirecting targeted sunlight to solar farms for extended energy harvesting hours"),
    "Relativity Space": ("space-launch-large", "3D-printed Terran R heavy-lift launch vehicle using robotic additive manufacturing to minimize part count and production time"),
    "Impulse Space": ("space-propulsion-engines", "Orbital kickstage and maneuvering vehicles providing precise last-mile payload delivery and in-space transportation services"),
    "K2 Space": ("space-satellites-buses", "Mega-class satellite buses leveraging cheap heavy-lift launch to build larger, more capable satellites at lower cost per capability"),
    "Vast": ("space-habitats-manufacturing", "Haven commercial space station — first privately developed orbital habitat for research, manufacturing, and space tourism"),
    "Northwood Space": ("space-ground-comms", "Phased array ground station network for high-throughput satellite data downlink using electronically steered antennas"),
    "Astranis": ("space-satellites-buses", "Small geostationary satellites delivering dedicated, affordable internet bandwidth to underserved regions worldwide"),
    "Observable Space": ("space-ground-comms", "Ground-based telescope systems and space optics for space domain awareness, tracking objects in orbit from Earth"),
    "Firefly Aerospace": ("space-launch-large", "Alpha small launch vehicle and Miranda lunar lander providing responsive launch services for government and commercial missions"),
    "Intuitive Machines": ("space-lunar-planetary", "Lunar lander and services company — first American company to land on the Moon since Apollo via Nova-C lander"),
    "Aalyria": ("space-ground-comms", "Multi-domain mesh networking using Tightbeam laser communications and Spacetime orchestration for contested environment connectivity"),
    "AnySignal": ("space-ground-comms", "End-to-end RF technology for satellite communications including antennas, modems, and ground systems for real-time data links"),
    "Turion Space": ("space-debris-servicing", "Space debris removal and orbital awareness using autonomous spacecraft for proximity operations and object characterization"),
    "Umbra": ("satellite-earth-observation", "High-resolution SAR satellite imaging cutting through clouds and darkness for persistent all-weather Earth observation"),
    "Albedo": ("satellite-earth-observation", "Very low Earth orbit satellites delivering unprecedented 10cm-resolution optical imagery from extremely close orbital altitudes"),
    "Blue Origin": ("space-launch-large", "New Shepard suborbital and New Glenn orbital launch vehicles plus Blue Moon lunar lander for cislunar transportation"),
    "Axiom Space": ("space-habitats-manufacturing", "Commercial space station development with attached ISS modules transitioning to free-flying station for research and manufacturing"),
    "Astrolab": ("space-lunar-planetary", "FLEX modular lunar rover designed for diverse payload transport and operations on the Moon's surface"),
    "Array Labs": ("satellite-earth-observation", "Satellite constellation for 3D mapping of the entire Earth from space using stereoscopic imaging from multiple angles"),
    "Armada": ("data-center-infrastructure", "Satellite-connected, rapidly deployable AI data centers for off-grid locations using modular, containerized computing infrastructure"),
    "Aetherflux": ("space-solar-power", "Space-based solar power using LEO satellites with infrared laser power beaming to ground receivers for 24/7 clean energy"),
    "Stoke Space": ("space-launch-large", "Fully reusable rocket with revolutionary reusable second stage using differential throttling ring of engines for propulsive landing"),
    "Capella Space": ("satellite-earth-observation", "SAR satellite constellation providing sub-0.5m resolution all-weather imaging with rapid revisit for defense and commercial clients"),
    "Muon Space": ("satellite-earth-observation", "Multi-sensor climate monitoring satellites combining multiple instruments per spacecraft for comprehensive environmental data collection"),
    "Planet Labs": ("satellite-earth-observation", "World's largest Earth-imaging satellite fleet capturing the entire planet daily at 3m resolution for change detection"),
    "Astroscale": ("space-debris-servicing", "Space debris removal using magnetic capture docking for proximity operations and end-of-life satellite deorbiting services"),
    "Outpost Space": ("space-habitats-manufacturing", "Reusable return capsules for on-demand cargo return from orbit, enabling space manufacturing and microgravity experiment retrieval"),
    "Longshot Space": ("space-propulsion-engines", "Electromagnetic launch cannon using pressurized air and linear motor to achieve orbit-capable velocities from ground launch"),
    "Proteus Space": ("space-propulsion-engines", "Advanced space propulsion systems and orbital maneuvering vehicles for flexible in-space transportation and mission profiles"),
    "Ursa Major Technologies": ("space-propulsion-engines", "Modular rocket engines using additive manufacturing for scalable propulsion systems serving both commercial and defense customers"),
    "AST SpaceMobile": ("space-ground-comms", "Large BlueBird satellites providing broadband directly to unmodified smartphones without requiring specialized ground terminals"),
    "Orbex": ("space-launch-small-intl", "Prime orbital launch vehicle with 3D-printed rocket engine and bio-propane fuel for low-carbon small satellite launches from Scotland"),
    "Space Forge": ("space-habitats-manufacturing", "Microgravity manufacturing of advanced materials and semiconductors using returnable satellite capsules for space-made products"),
    "Isar Aerospace": ("space-launch-small-intl", "Spectrum launch vehicle — Europe's commercial answer to Falcon 9 economics for dedicated small and medium satellite missions"),
    "Rocket Factory Augsburg": ("space-launch-small-intl", "RFA One orbital launch vehicle using staged combustion engines for cost-effective small satellite delivery from European spaceports"),
    "Latitude": ("space-launch-small-intl", "Zephyr micro-launcher for dedicated small satellite deployment from French Guiana using hybrid solid-liquid propulsion"),
    "ICEYE": ("satellite-earth-observation", "World's largest commercial SAR constellation providing persistent radar imaging for flood monitoring, defense, and maritime tracking"),
    "PLD Space": ("space-launch-small-intl", "MIURA family of launch vehicles — first Spanish orbital rocket company with successful suborbital demonstration flights"),
    "D-Orbit": ("space-debris-servicing", "ION orbital transfer vehicle providing precise satellite deployment, in-orbit services, and end-of-life disposal using hosted payloads"),
    "Ramon.Space": ("space-satellites-buses", "Radiation-hardened computing hardware building space-grade supercomputers that operate reliably in the harsh space radiation environment"),
    "ispace": ("space-lunar-planetary", "Lunar exploration company building landers and rovers for commercial payload delivery to the Moon for science and resources"),
    "Innospace": ("space-launch-small-intl", "HANBIT hybrid rocket launch vehicle for small satellite delivery, first Korean private rocket with successful suborbital flight"),
    "Skyroot Aerospace": ("space-launch-small-intl", "India's first private rocket company reaching space with Vikram series using 3D-printed engines and solid-liquid hybrid stages"),
    "Agnikul Cosmos": ("space-launch-small-intl", "World's first single-piece 3D-printed semi-cryogenic rocket engine enabling customizable, on-demand small satellite launches from India"),
    "Pixxel": ("satellite-earth-observation", "Hyperspectral Earth-imaging satellites capturing 150+ spectral bands for precision agriculture, environmental, and mineral analysis"),
    "Fleet Space Technologies": ("satellite-earth-observation", "Phased-array satellite constellation combined with ambient noise tomography for mineral exploration from orbit"),
    "Satellogic": ("satellite-earth-observation", "Sub-meter resolution Earth observation satellites at low cost, building Latin America's first commercial imaging constellation"),
    "Dawn Aerospace": ("space-launch-small-intl", "Reusable spaceplane technology using horizontal takeoff and landing for daily orbital access and green satellite propulsion"),
    "Dragonfly Aerospace": ("satellite-earth-observation", "High-resolution imaging payloads and small Earth observation satellites built in South Africa for global customers"),
    "Starpath Robotics": ("space-lunar-planetary", "In-situ resource utilization technology producing rocket propellant from lunar and Martian surface materials"),
    "LeoLabs": ("space-ground-comms", "Space situational awareness using phased-array radar network to track objects in LEO with centimeter-level precision"),
    "Slingshot Aerospace": ("space-ground-comms", "AI-based satellite tracking and space traffic coordination using ML to predict orbital conjunctions and collision risks"),
    "Kepler Communications": ("space-ground-comms", "Satellite network enabling high-bandwidth data relay in space using optical inter-satellite links for space-to-space connectivity"),
    "GHGSat": ("satellite-earth-observation", "World's largest fleet of methane-monitoring satellites using high-resolution spectroscopy to pinpoint individual facility emissions"),
    "Reaction Dynamics": ("space-launch-small-intl", "Low-cost hybrid rocket technology combining solid fuel grains with liquid oxidizer for affordable small satellite launches"),
    "Endurosat": ("space-satellites-buses", "Nanosatellite manufacturer providing shared satellite-as-a-service platform for rapid, affordable space mission deployment"),
    "Skyryse": ("evtol-air-taxi", "AI-powered pilot assistance (FlightOS) making any aircraft fly-by-wire autonomous, starting with helicopters for safer aviation"),
    "Poseidon Aerospace": ("maritime-electric-transport", "Ground-effect vehicle (ekranoplan) using modern composites and electric propulsion to fly cargo just above water at high speed"),

    # === Space Systems ===
    "Starcloud": ("data-center-infrastructure", "Space-based cloud computing deploying data centers in orbit for reduced latency and unlimited cooling via space environment"),
    "Celero Communications": ("space-ground-comms", "Direct-to-device satellite communications enabling global smartphone connectivity without specialized satellite phone hardware"),
    "Hubble Network": ("space-ground-comms", "Satellite network connecting any Bluetooth-enabled device globally using LEO satellites with custom signal processing"),
    "ClearSpace": ("space-debris-servicing", "Active debris removal spacecraft using robotic capture arms, contracted by ESA for the first commercial debris removal mission"),
    "Terran Orbital": ("space-satellites-buses", "End-to-end satellite solutions from design through manufacturing and operations for small and medium satellite constellations"),
    "Skyrora": ("space-launch-small-intl", "Skyrora XL orbital launch vehicle for small satellite delivery from UK-based vertical launch facilities"),
    "Orbion Space Technology": ("space-propulsion-engines", "Hall-effect plasma thrusters for small satellite propulsion enabling precise orbital maneuvering with electric propulsion"),
    "Orbit2Orbit": ("space-debris-servicing", "Reusable in-space logistics vehicles that remain in orbit permanently, providing station-to-station cargo transport services"),
    "PierSight": ("satellite-earth-observation", "Combined SAR and AIS satellite constellation — world's first dual-sensor platform for comprehensive maritime surveillance"),
    "Mynaric": ("space-ground-comms", "Laser optical inter-satellite link terminals enabling 10 Gbps data highways between satellites using free-space laser communications"),

    # === Supersonic & Hypersonic ===
    "Boom Supersonic": ("supersonic-hypersonic-transport", "Overture Mach 1.7 commercial supersonic airliner using four turbojet engines and sustainable aviation fuel for trans-oceanic routes"),
    "Hermeus": ("supersonic-hypersonic-transport", "Mach 5+ hypersonic jet with hybrid Chimera engine transitioning from turbofan to ramjet for hypersonic commercial and military flight"),
    "Astro Mechanica": ("supersonic-hypersonic-transport", "Electric Adaptive Engine using electromagnetic compression to transition from subsonic turbofan to supersonic ramjet in a single powerplant"),
    "Venus Aerospace": ("supersonic-hypersonic-transport", "Mach 9+ hypersonic vehicles using rotating detonation engines for both commercial point-to-point transport and defense applications"),
    "Exosonic": ("supersonic-hypersonic-transport", "Low-boom supersonic airliner designed to minimize sonic boom intensity for overland supersonic flight using shaped fuselage"),
    "Destinus": ("supersonic-hypersonic-transport", "Hydrogen-powered hypersonic aircraft using liquid hydrogen fuel for cargo transport at Mach 5+ speeds with zero carbon emissions"),
    "Dynamo Air": ("supersonic-hypersonic-transport", "Next-generation supersonic flight technology for commercial and defense applications using advanced aerodynamic design"),

    # === Transportation ===
    "The Boring Company": ("logistics-supply-chain", "Underground transit tunnels using custom tunnel boring machines for urban transportation and hyperlogistics networks"),
    "Pipedream": ("logistics-supply-chain", "Underground hyperlogistics using small-diameter pneumatic tubes for automated last-mile package delivery beneath city streets"),
    "Navier": ("maritime-electric-transport", "Electric hydrofoil boats flying above water on computer-controlled foils for zero-wake, energy-efficient maritime transport"),
    "Arc Boats": ("maritime-electric-transport", "High-performance electric boats combining advanced battery technology with luxury marine design for emission-free boating"),
    "Lumina Vehicles": ("transport-electric-vehicles", "Next-gen electric vehicles with advanced autonomous capabilities combining EV powertrain with self-driving technology"),
    "FleetZero": ("maritime-electric-transport", "Battery-electric container ships using modular swappable battery containers to convert fossil-fuel vessels to electric power"),
    "Vertical Aerospace": ("evtol-air-taxi", "VX4 electric air taxi with four tilting rotors for 100-mile range urban air mobility, partnered with American Airlines"),
    "ZeroAvia": ("electrolysis-green-hydrogen", "Hydrogen-electric aviation powertrains replacing jet engines with fuel cell systems for zero-emission regional aircraft flights"),
    "Volocopter": ("evtol-air-taxi", "Electric air taxi using distributed multirotor design for urban air mobility with EASA type certification pathway"),
    "Einride": ("ai-autonomous-driving", "Autonomous electric freight trucks using pod-like cabless design with remote operation capability for depot-to-depot logistics"),
    "Zoox": ("ai-autonomous-driving", "Purpose-designed bidirectional autonomous robotaxi for urban mobility, owned by Amazon, with no traditional driver controls"),
    "Harbinger": ("transport-electric-vehicles", "Electric commercial vehicle chassis architecture designed ground-up for medium-duty fleet electrification"),
    "Parallel Systems": ("logistics-supply-chain", "Autonomous battery-electric freight rail vehicles operating independently on existing rail infrastructure for flexible cargo routing"),
    "Revel": ("transport-electric-vehicles", "Largest public EV fast-charging network in NYC plus electric moped sharing for urban electric mobility infrastructure"),
    "Rivian": ("transport-electric-vehicles", "Electric adventure vehicles (R1S, R1T) and commercial delivery vans with Amazon partnership for fleet electrification"),
    "Waabi": ("ai-autonomous-driving", "Simulation-first autonomous trucking using generative AI to create billions of driving scenarios for training without real-world miles"),
    "REGENT Craft": ("maritime-electric-transport", "Electric seagliders using wing-in-ground-effect to fly just above water at 180mph on battery power for coastal transport"),

    # Additional assignments for Edge Cases
    "Elroy Air": ("autonomy-delivery-logistics", "Chaparral hybrid-electric autonomous VTOL cargo drone for middle-mile logistics in remote and underserved areas"),
}

def main():
    with open('data.js', 'r') as f:
        content = f.read()

    # Find all company entries and add thesisCluster + techApproach
    updated = 0
    skipped = 0
    missing = []

    for company_name, (cluster, approach) in COMPANY_DATA.items():
        # Validate cluster exists
        if cluster not in CLUSTER_LABELS:
            print(f"WARNING: Unknown cluster '{cluster}' for {company_name}")
            continue

        # Check if this company already has thesisCluster
        # Find the company entry by name
        pattern = rf'(name:\s*"{re.escape(company_name)}")'
        if not re.search(pattern, content):
            if company_name not in ("Cuby",):  # Skip known aliases
                skipped += 1
            continue

        # Check if thesisCluster already exists for this entry
        # Find the block for this company
        name_match = re.search(pattern, content)
        if not name_match:
            continue

        # Check if already has thesisCluster after this name (within next 500 chars)
        after_name = content[name_match.start():name_match.start() + 800]
        if 'thesisCluster:' in after_name:
            skipped += 1
            continue

        # Escape the approach string for JS
        approach_escaped = approach.replace('"', '\\"').replace("'", "\\'")

        # Find the addedDate line for this company and add fields before it
        # Strategy: find `name: "CompanyName"` then find the next `addedDate:` line
        pos = name_match.start()
        added_date_pattern = r'(    addedDate: "[\d-]+")'
        added_match = re.search(added_date_pattern, content[pos:pos+2000])

        if added_match:
            insert_pos = pos + added_match.start()
            new_fields = f'    thesisCluster: "{cluster}",\n    techApproach: "{approach_escaped}",\n'
            content = content[:insert_pos] + new_fields + content[insert_pos:]
            updated += 1
        else:
            # Try alternative: insert before competitors or tags line
            tags_pattern = r'(    tags: \[)'
            tags_match = re.search(tags_pattern, content[pos:pos+2000])
            if tags_match:
                insert_pos = pos + tags_match.start()
                new_fields = f'    thesisCluster: "{cluster}",\n    techApproach: "{approach_escaped}",\n'
                content = content[:insert_pos] + new_fields + content[insert_pos:]
                updated += 1
            else:
                missing.append(company_name)

    # Write updated content
    with open('data.js', 'w') as f:
        f.write(content)

    print(f"\n{'='*60}")
    print(f"  Thesis fields added to {updated} companies")
    print(f"  Skipped (already had fields or not found): {skipped}")
    if missing:
        print(f"  Could not find insertion point for: {missing}")
    print(f"  File size: {len(content)} bytes ({len(content)/1024:.0f}KB)")
    print(f"{'='*60}")

if __name__ == '__main__':
    main()
