#!/usr/bin/env python3
"""
Founder benchmark data — one compact record per tracked company for benchmark.html.
─────────────────────────────────────────────────────────────────────────
Reads the Pulse snapshots, the event feeds, the intel lists and the milestones file and writes
data/pulse_companies_auto.js:

  const PULSE_COMPANIES = {
    generated, months: [...],
    medians: { bucket: { roles, growth3m_pct, atoms_bits, panel } },   # current month, panel companies
    companies: { name: { b, st, r[], m[], s[], sr[], cap, con, sc, rk, n, rung, ff, atr, atb, board } }
  }

Free, for every founder. Nothing here can be bought or edited by the company; corrections go
through the review queue.
"""
import json
import statistics
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from calc_pulse import DATA, OUT, SNAP, load_companies, in_universe, capital_events, contract_events  # noqa: E402


def main():
    companies = load_companies()
    snaps = {p.stem: json.load(open(p)) for p in sorted(SNAP.glob("*.json"))}
    months = [m for m in sorted(snaps) if m >= "2026-04"]
    cur = months[-1]
    cap, _ = capital_events(companies)
    con = contract_events(companies)
    scores = {}
    p = OUT / f"company_scores_{cur}.json"
    if p.exists():
        for r in json.load(open(p))["top"]:
            scores[r["company"]] = r["score"]
    # full score list is only top 50 in that file; recompute rank from all universe scores in intel if present
    intel = json.load(open(OUT / f"intel_{cur}.json")) if (OUT / f"intel_{cur}.json").exists() else {}
    atr = {x["company"] for x in intel.get("about_to_raise", [])}
    atb = {x["company"] for x in intel.get("about_to_build", [])}
    rungs = {}
    p = OUT / "milestones.json"
    if p.exists():
        for r in json.load(open(p)):
            if r.get("confirmed", True) and r.get("rung_to") is not None:
                rungs[r["company"]] = max(rungs.get(r["company"], 0), int(r["rung_to"]))

    cur_roles = snaps[cur]["roles"]
    prev3 = snaps[months[-4]]["roles"] if len(months) >= 4 else snaps[months[0]]["roles"]
    out, by_bucket = {}, defaultdict(list)
    for n, c in companies.items():
        if not in_universe(c):
            continue
        r = [snaps[m]["roles"].get(n) for m in months]
        mm = [snaps[m]["mfg"].get(n, 0) if snaps[m]["roles"].get(n) is not None else None for m in months]
        ss = [snaps[m]["sw"].get(n, 0) if snaps[m]["roles"].get(n) is not None else None for m in months]
        sr = [snaps[m].get("senior", {}).get(n, 0) if snaps[m]["roles"].get(n) is not None else None for m in months]
        has_board = r[-1] is not None
        rec = {"b": c["bucket"], "st": c.get("state", ""), "r": r, "m": mm, "s": ss, "sr": sr,
               "cap": (cap.get(n) or [None])[-1], "con": (con.get(n) or [None])[-1],
               "sc": scores.get(n), "rung": rungs.get(n), "ff": bool(sr[-1]) if sr[-1] else False,
               "atr": n in atr, "atb": n in atb, "board": has_board}
        out[n] = rec
        if has_board:
            by_bucket[c["bucket"]].append(n)

    # ranks within bucket by current roles growth (3m) then roles; medians per bucket
    medians = {}
    for b, names in by_bucket.items():
        rows = []
        for n in names:
            now, back = cur_roles.get(n, 0), prev3.get(n)
            g = (now - back) / back * 100 if back else None
            ab = (snaps[cur]["mfg"].get(n, 0) / snaps[cur]["sw"].get(n, 1)) if snaps[cur]["sw"].get(n, 0) else None
            rows.append((n, now, g, ab))
        ranked = sorted(rows, key=lambda x: (-(x[2] if x[2] is not None else -1e9), -x[1]))
        for i, (n, *_r) in enumerate(ranked, 1):
            out[n]["rk"] = i
            out[n]["n"] = len(ranked)
        gs = [x[2] for x in rows if x[2] is not None]; abs_ = [x[3] for x in rows if x[3] is not None]
        medians[b] = {"roles": statistics.median([x[1] for x in rows]) if rows else None,
                      "growth3m_pct": round(statistics.median(gs), 1) if gs else None,
                      "atoms_bits": round(statistics.median(abs_), 2) if abs_ else None, "panel": len(rows)}

    payload = {"generated": date.today().isoformat(), "months": months, "medians": medians, "companies": out}
    with open(DATA / "pulse_companies_auto.js", "w") as f:
        f.write("// Auto-generated by scripts/build_pulse_companies.py — founder benchmark data (free)\n")
        f.write("const PULSE_COMPANIES = " + json.dumps(payload, separators=(",", ":")) + ";\n")
    print(f"companies: {len(out)} (with a board this month: {sum(1 for v in out.values() if v['board'])}); buckets: {len(medians)}")
    for b, m in sorted(medians.items()):
        print(f"  {b:26s} panel={m['panel']:3d} median roles={m['roles']} growth3m={m['growth3m_pct']}% a/b={m['atoms_bits']}")


if __name__ == "__main__":
    main()
