#!/usr/bin/env python3
"""
Round 7l — Emit browser-ready data/<name>_auto.js files from the 9 auto.json
outputs produced by Round 7l calc scripts. Each emitted file exposes a single
global constant (e.g. FIELD_NOTES_AUTO) so pages can <script src=...> them
without touching the main data.js.

Source → destination mapping:
  field_notes_auto.json          → FIELD_NOTES_AUTO          → data/field_notes_auto.js
  budget_signals_auto.json       → BUDGET_SIGNALS_AUTO       → data/budget_signals_auto.js
  fund_intelligence_auto.json    → FUND_INTELLIGENCE_AUTO    → data/fund_intelligence_auto.js
  ma_comps_auto.json             → MA_COMPS_AUTO             → data/ma_comps_auto.js
  founder_mafias_auto.json       → FOUNDER_MAFIAS_AUTO       → data/founder_mafias_auto.js
  network_graph_auto.json        → NETWORK_GRAPH_AUTO        → data/network_graph_auto.js
  contractor_readiness_auto.json → CONTRACTOR_READINESS_AUTO → data/contractor_readiness_auto.js
  gov_demand_summary_auto.json   → GOV_DEMAND_SUMMARY_AUTO   → data/gov_demand_summary_auto.js
  expert_takes_auto.json         → EXPERT_TAKES_AUTO         → data/expert_takes_auto.js

Safe to re-run. No-op on any missing source files. Writes nothing if source
is empty.
"""

import json
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"

MAPPINGS = [
    ("field_notes_auto.json",          "FIELD_NOTES_AUTO"),
    ("budget_signals_auto.json",       "BUDGET_SIGNALS_AUTO"),
    ("fund_intelligence_auto.json",    "FUND_INTELLIGENCE_AUTO"),
    ("ma_comps_auto.json",             "MA_COMPS_AUTO"),
    ("founder_mafias_auto.json",       "FOUNDER_MAFIAS_AUTO"),
    ("network_graph_auto.json",        "NETWORK_GRAPH_AUTO"),
    ("contractor_readiness_auto.json", "CONTRACTOR_READINESS_AUTO"),
    ("gov_demand_summary_auto.json",   "GOV_DEMAND_SUMMARY_AUTO"),
    ("expert_takes_auto.json",         "EXPERT_TAKES_AUTO"),
]


def emit_one(src_name, const_name):
    src = DATA_DIR / src_name
    if not src.exists():
        print(f"  [skip] {src_name} does not exist")
        return False
    try:
        data = json.loads(src.read_text())
    except Exception as e:
        print(f"  [skip] {src_name} is not valid JSON ({e})")
        return False
    # Empty-payload guard. List → len, dict → truthiness of any value.
    if isinstance(data, list) and len(data) == 0:
        print(f"  [skip] {src_name} is an empty list; refusing to emit empty global")
        return False
    if isinstance(data, dict) and not any(data.get(k) for k in data):
        print(f"  [skip] {src_name} has no non-empty keys")
        return False

    # Stamp with generated timestamp when not already present
    if isinstance(data, dict) and "generated_at" not in data:
        data["generated_at"] = datetime.utcnow().isoformat() + "Z"

    out = DATA_DIR / src_name.replace(".json", ".js")
    header = (
        f"// Auto-generated by scripts/emit_round7l_auto_js.py\n"
        f"// Source: data/{src_name}\n"
        f"// Last updated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC\n"
    )
    body = f"const {const_name} = {json.dumps(data, indent=2, ensure_ascii=False)};\n"
    out.write_text(header + body)
    size = len(data) if isinstance(data, list) else len(data.keys())
    print(f"  [ok]   {const_name:28s}  {src_name:36s} ({size} entries) → {out.name}")
    return True


def main():
    print("=" * 60)
    print("Round 7l — Auto.js emit step")
    print("=" * 60)
    emitted = 0
    for src, const in MAPPINGS:
        if emit_one(src, const):
            emitted += 1
    print(f"\n  Emitted {emitted}/{len(MAPPINGS)} auto.js files")


if __name__ == "__main__":
    main()
