#!/usr/bin/env python3
"""Generate human-readable verification report from company_facts_verification.json."""

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IN_PATH = ROOT / "data" / "company_facts_verification.json"
OUT_PATH = ROOT / "COMPANY_FACTS_VERIFICATION_REPORT.md"


def main():
    if not IN_PATH.exists():
        print(f"⚠ {IN_PATH} not found")
        return 1
    d = json.load(open(IN_PATH))
    if d.get('skipped'):
        OUT_PATH.write_text(f"# Verification skipped\n\nReason: {d.get('reason')}\n")
        return 0

    summary = d.get('summary', {})
    cleared = d.get('cleared', [])
    changes = d.get('changesProposed', [])
    unverifiable = d.get('unverifiable', [])

    md = []
    md.append(f"# Company Facts Verification Report\n")
    md.append(f"**Generated:** {d.get('generatedAt','?')}  \n")
    md.append(f"**Cohort:** `{d.get('cohortFile','?')}`  \n")
    md.append(f"**Cohort size:** {d.get('cohortSize',0)} companies  \n")
    md.append(f"**New Claude extractions this run:** {d.get('newExtractionsThisRun',0)}  \n")
    md.append("")
    md.append("## Summary")
    md.append("")
    md.append(f"| Category | Count | % |")
    md.append(f"|---|---|---|")
    n = max(d.get('cohortSize', 1), 1)
    md.append(f"| ✅ Cleared (data matches sources) | {summary.get('cleared',0)} | {100*summary.get('cleared',0)/n:.0f}% |")
    md.append(f"| 🔧 Changes proposed | {summary.get('changesProposed',0)} | {100*summary.get('changesProposed',0)/n:.0f}% |")
    md.append(f"| ❓ Unverifiable | {summary.get('unverifiable',0)} | {100*summary.get('unverifiable',0)/n:.0f}% |")
    md.append("")
    md.append("---")
    md.append("")

    # Section 1: Changes proposed (most actionable)
    if changes:
        md.append(f"## 🔧 Proposed Changes ({len(changes)} companies)")
        md.append("")
        md.append("Review each change and reply with which ones to apply. **Source-cited diffs:**")
        md.append("")
        for entry in changes:
            md.append(f"### {entry['name']}")
            md.append("")
            for ch in entry['changes']:
                cur = str(ch.get('current') or '*(empty)*')
                ver = str(ch.get('verified'))
                src_idxs = ch.get('sources') or []
                src_links = []
                for idx in src_idxs:
                    if isinstance(idx, int) and idx < len(entry.get('sources', [])):
                        s = entry['sources'][idx]
                        url = s.get('url')
                        if url:
                            src_links.append(f"[{s['src']}]({url})")
                        else:
                            src_links.append(s['src'])
                src_str = " · ".join(src_links) if src_links else "*(no sources cited)*"
                md.append(f"- **`{ch['field']}`:** `{cur[:60]}` → `{str(ver)[:60]}`  ")
                md.append(f"  Sources: {src_str}")
            if entry.get('notes'):
                md.append(f"\n  **Notes:** {entry['notes']}")
            md.append("")
        md.append("---")
        md.append("")

    # Section 2: Unverifiable
    if unverifiable:
        md.append(f"## ❓ Unverifiable ({len(unverifiable)} companies)")
        md.append("")
        md.append("Couldn't fetch authoritative sources. Per Stephen's rule, "
                 "we leave these as-is rather than guess. May want to flag for "
                 "manual research or removal from DB.")
        md.append("")
        for entry in unverifiable[:30]:
            md.append(f"- **{entry['name']}** — *{entry.get('reason','?')}*")
        if len(unverifiable) > 30:
            md.append(f"- *...and {len(unverifiable)-30} more*")
        md.append("")
        md.append("---")
        md.append("")

    # Section 3: Cleared (just count + sample)
    if cleared:
        md.append(f"## ✅ Cleared ({len(cleared)} companies)")
        md.append("")
        md.append(f"Data matches sources for these companies — **no changes needed**.")
        md.append("")
        md.append("Sample (first 30):")
        md.append("")
        for nm in cleared[:30]:
            md.append(f"- {nm}")
        if len(cleared) > 30:
            md.append(f"- *...and {len(cleared)-30} more*")
        md.append("")

    md.append("")
    md.append(f"---")
    md.append(f"")
    md.append(f"*Generated by `scripts/generate_verification_report.py` on "
              f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}*")

    OUT_PATH.write_text("\n".join(md))
    print(f"✅ Wrote {OUT_PATH.relative_to(ROOT)} ({len(md)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
