#!/usr/bin/env python3
"""
Inject cluster sub-nav into pages that belong to a cluster.

Two clusters defined:
  CAPITAL_CLUSTER   = the 7 Capital-tab pages
  CALENDAR_CLUSTER  = the 5 Calendar-tab pages

Each page gets a horizontal sub-nav strip just below its main <header
class="il-hero"> (or just below </nav> if no hero). The current page is
auto-highlighted via aria-current="page".

Pages NOT yet using the .il-* component library (everything except the 3
new ones) get a fallback inline-styled strip so they look right too.

Re-runnable; idempotent (skips pages that already have a sub-nav).

Usage:
  python scripts/inject_subnav.py [--dry-run]
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Cluster definitions: filename → display label
CLUSTERS = {
    "capital": [
        ("investors.html",             "👥 Investors"),
        ("investor-intelligence.html", "🕸 Intelligence"),
        ("investor-hub.html",          "💼 Hub"),
        ("baskets.html",               "💰 Public Baskets"),
        ("valuations.html",            "📉 Valuations"),
        ("captable.html",              "📋 Cap Tables"),
        ("govradar.html",              "🎖️ Gov Radar"),
    ],
    "calendar": [
        ("catalysts.html",         "🎯 Catalysts"),
        ("calendar.html",          "📅 Industry Events"),
        ("launches.html",          "🛰️ Launches"),
        ("earnings-signals.html",  "📈 Earnings"),
        ("regulatory.html",        "📋 Regulatory"),
    ],
}

PAGE_TO_CLUSTER = {}
for cluster, pages in CLUSTERS.items():
    for fname, _ in pages:
        PAGE_TO_CLUSTER[fname] = cluster


def render_subnav(cluster_id, current_filename, label_prefix):
    """Render the sub-nav HTML, marking current page as active."""
    pages = CLUSTERS[cluster_id]
    links = []
    for fname, label in pages:
        active = fname == current_filename
        attr = ' aria-current="page"' if active else ""
        links.append(f'      <a href="{fname}" class="il-subnav__link"{attr}>{label}</a>')
    return (
        '    <!-- Cluster sub-nav (auto-generated by scripts/inject_subnav.py) -->\n'
        '    <div class="il-subnav">\n'
        '      <div class="il-subnav__inner">\n'
        f'        <span class="il-subnav__label">{label_prefix}</span>\n'
        + "\n".join(links) + "\n"
        '      </div>\n'
        '    </div>'
    )


# Existing sub-nav (idempotency check)
SUBNAV_RE = re.compile(r'<!--\s*Cluster sub-nav[^>]*-->\s*\n\s*<div class="il-subnav">[\s\S]*?</div>\s*</div>',
                       re.IGNORECASE)


def page_has_il_styles(src):
    """True if page already imports the shared component library."""
    return "css/_components.css" in src or "_tokens.css" in src


def inject(path, dry_run=False):
    fname = path.name
    cluster = PAGE_TO_CLUSTER.get(fname)
    if not cluster:
        return ("skip", "not in any cluster")

    src = path.read_text(encoding="utf-8")

    # Check if page imports the component library; inject it if not so the
    # sub-nav styles work.
    needs_components_import = "css/_components.css" not in src

    label_prefix = "Capital" if cluster == "capital" else "Calendar"
    new_subnav = render_subnav(cluster, fname, label_prefix)

    # Replace existing if present (idempotent) — match the new pattern with
    # explicit </div></div> closure
    existing = re.search(
        r'    <!-- Cluster sub-nav[^>]*-->\s*\n    <div class="il-subnav">[\s\S]*?\n    </div>',
        src,
    )
    if existing:
        if existing.group(0) == new_subnav:
            return ("noop", "already correct")
        src = src[:existing.start()] + new_subnav + src[existing.end():]
        change_msg = "replaced existing"
    else:
        # Place after </nav>
        nav_end = src.find('</nav>')
        if nav_end < 0:
            return ("skip", "no </nav> found")
        # Insert two newlines after the </nav>
        insert_at = nav_end + len('</nav>')
        src = src[:insert_at] + '\n\n' + new_subnav + src[insert_at:]
        change_msg = "inserted after </nav>"

    # Inject component library imports if not already present
    if needs_components_import:
        head_end = src.find('</head>')
        if head_end > 0:
            # Insert right before </head>
            imports = (
                '    <link rel="stylesheet" href="css/_tokens.css?v=20260501" />\n'
                '    <link rel="stylesheet" href="css/_components.css?v=20260501" />\n'
            )
            src = src[:head_end] + imports + src[head_end:]
            change_msg += " + added _tokens/_components imports"

    if dry_run:
        return ("preview", change_msg)
    path.write_text(src, encoding="utf-8")
    return ("ok", change_msg)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    print("=" * 64)
    print(f"Sub-nav injection — {'DRY RUN' if args.dry_run else 'APPLY'}")
    print("=" * 64)

    targets = sorted({fname for fnames in CLUSTERS.values() for fname, _ in fnames})
    summary = {"ok": 0, "noop": 0, "skip": 0, "preview": 0}

    for fname in targets:
        path = ROOT / fname
        if not path.exists():
            print(f"  ⏭ {fname:<35} file not found")
            summary["skip"] += 1
            continue
        status, msg = inject(path, dry_run=args.dry_run)
        sym = {"ok": "✓", "noop": "·", "skip": "⏭", "preview": "→"}.get(status, "?")
        print(f"  {sym} {fname:<35} {msg}")
        summary[status] = summary.get(status, 0) + 1

    print()
    print(f"Summary: {summary}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
