#!/usr/bin/env bash
#
# Sync the public ROS database into the member site (investors.rationaloptimistsociety.com).
#
#   ./scripts/sync_to_member_site.sh          # sync, verify, push to dev, open PR
#   ./scripts/sync_to_member_site.sh --dry    # show what would change, touch nothing
#
# The member site is a STATIC site: all 26 pages load /data.js and read the global
# COMPANIES array. There is no database read path for company display, so copying
# data.js updates Companies/map, Investors, Valuations, Tech Readiness and Data Viz
# at once. scripts/seed-companies.ts in the app repo is NOT part of this flow.
#
# Two files carry data, not one:
#   frontend/public/data.js            -> every page except il30.html
#   frontend/public/data/il30-static.js -> il30.html only (its own roster + blurbs)
#
set -euo pipefail

PUB="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="${APP_REPO:-$HOME/Desktop/Claude/innovators-league-app}"
DRY=0; [[ "${1:-}" == "--dry" ]] && DRY=1

# The macOS keychain helper is broken for this repo; route auth through gh.
# Must be a function, not a variable — the helper string contains spaces.
gitx() { git -c "credential.helper=!gh auth git-credential" "$@"; }

[[ -d "$APP/.git" ]] || { echo "app repo not found at $APP (set APP_REPO=)"; exit 1; }

echo "==> gate the source database first"
python3 "$PUB/scripts/validate_data_quality.py" || { echo "ABORT: source data.js failed the quality gate"; exit 1; }

cd "$APP"
gitx fetch -q origin
git checkout -q dev && gitx pull -q origin dev

echo "==> copying data.js"
[[ $DRY -eq 0 ]] && cp "$PUB/data.js" frontend/public/data.js

echo "==> refreshing auto-data feeds the member site actually loads"
n=0
for f in $(grep -rhoE 'src="/data/[a-z0-9_.-]+\.js"' frontend/index.html frontend/public/*.html \
           | sed 's|src="/data/||;s|"||' | sort -u); do
  [[ -f "$PUB/data/$f" && -f "frontend/public/data/$f" ]] || continue
  cmp -s "$PUB/data/$f" "frontend/public/data/$f" && continue
  [[ $DRY -eq 0 ]] && cp "$PUB/data/$f" "frontend/public/data/$f"
  n=$((n+1))
done
echo "    $n feed(s) refreshed"

if [[ $DRY -eq 1 ]]; then
  echo "==> DRY RUN, reverting"; git checkout -- frontend/public 2>/dev/null || true
  git status --short; exit 0
fi

echo "==> verifying"
for f in frontend/public/data.js frontend/public/data/*.js; do
  node --check "$f" >/dev/null || { echo "PARSE FAIL: $f"; exit 1; }
done

# Every page, script-by-script, in its own scope: catches duplicate-const collisions
# between data.js and the per-page static files (il30-static, trl-static, viz-static...).
node - <<'JS' || exit 1
const fs=require("fs"),vm=require("vm"),path=require("path");
const pages=["frontend/index.html",...fs.readdirSync("frontend/public").filter(f=>f.endsWith(".html")).map(f=>"frontend/public/"+f)];
let bad=0;
for(const p of pages){
  const srcs=[...fs.readFileSync(p,"utf8").matchAll(/src="(\/?[a-z0-9_.\/-]+\.js)(\?[^"]*)?"/gi)].map(m=>m[1]);
  const local=srcs.map(s=>"frontend/public/"+s.replace(/^\//,"")).filter(f=>fs.existsSync(f));
  if(!local.length) continue;
  const sb={console:{log(){},warn(){},error(){}},window:{},navigator:{userAgent:""},localStorage:{getItem:()=>null,setItem(){}},location:{href:"",search:"",pathname:"/"},fetch:()=>Promise.resolve({json:()=>({})}),setTimeout(){},addEventListener(){},
    document:{addEventListener(){},querySelector:()=>null,querySelectorAll:()=>[],getElementById:()=>null,createElement:()=>({style:{},classList:{add(){},remove(){}},appendChild(){}})}};
  sb.globalThis=sb; vm.createContext(sb);
  for(const f of local){
    try{ vm.runInContext(fs.readFileSync(f,"utf8"),sb,{filename:f}); }
    catch(e){ if(/already been declared/.test(e.message)){ console.log("COLLISION "+path.basename(p)+" <- "+path.basename(f)+": "+e.message); bad++; } }
  }
}
if(bad){ console.log(bad+" collision(s) — not shipping"); process.exit(1); }
console.log("    "+pages.length+" pages checked, 0 declaration collisions");
JS

# No company silently dropped.
node -e '
const fs=require("fs"),vm=require("vm");
const g=p=>{const s={};vm.createContext(s);vm.runInContext(fs.readFileSync(p,"utf8")+";globalThis.__c=COMPANIES;",s);return s.__c.map(c=>c.name);};
const before=g("/tmp/_prev_data.js"), after=g("frontend/public/data.js");
const lost=before.filter(n=>!after.includes(n));
if(lost.length) console.log("    NOTE dropped (check these are renames): "+lost.join(", "));
' 2>/dev/null || true

git add -A frontend/public/data.js frontend/public/data/
git diff --cached --quiet && { echo "==> nothing changed, member site already current"; exit 0; }

STAMP=$(date +%Y-%m-%d)
COUNT=$(node -e 'const fs=require("fs"),vm=require("vm");const s={};vm.createContext(s);vm.runInContext(fs.readFileSync("frontend/public/data.js","utf8")+";globalThis.__n=COMPANIES.length;",s);console.log(s.__n)')
git commit -q -m "content: sync member site to the ROS database ($COUNT companies, $STAMP)

Data only. No code, schema or infrastructure changes.
Generated by scripts/sync_to_member_site.sh in the public repo.

Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>"

gitx push -q origin dev
echo "==> pushed to dev, auto-deploy takes ~3 min: https://dev.investors.rationaloptimistsociety.com"
echo "==> when dev looks right, open the PR to main with:"
echo "    gh pr create --repo MauldinEconomics/innovators-league-app --base main --head dev \\"
echo "      --title 'content: sync member site to ROS database ($STAMP)' --body '...'"
