#!/usr/bin/env python3
"""
Unify navigation across every HTML page on the site.

Background: after Sprints 1-4 added 3 new pages (catalysts, baskets,
investor-intelligence), only those 3 pages had updated nav. The other 29
pages still pointed to the old structure — users on most pages couldn't
discover the new features.

This script replaces the existing `<nav class="nav">…</nav>` block on
every .html file with a canonical version reflecting the new IA:

  Companies | Terminal | Calendar | Capital | Signals | Research

The current-page link gets highlighted automatically.

Usage:
  python scripts/unify_nav.py [--dry-run]
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# ─── CANONICAL NAV TEMPLATE ───────────────────────────────────────────
# Each link tagged with data-nav-id matching the filename so we can
# highlight the active page programmatically. Order reflects the new IA.

NAV_TEMPLATE = '''    <!-- Navigation — unified IA (auto-generated by scripts/unify_nav.py) -->
    <nav class="nav">
        <div class="nav-brand">
            <a href="index.html" style="display:flex;align-items:center;gap:8px;text-decoration:none;">
                <div class="nav-logo">ROS</div>
                <span class="nav-title">THE INNOVATORS LEAGUE</span>
            </a>
        </div>
        <div class="nav-links">
            <a href="index.html" class="nav-link" data-nav-id="index">Companies</a>
            <a href="terminal.html" class="nav-link" data-nav-id="terminal" style="color:#86efac;">⚡ Terminal</a>

            <div class="nav-dropdown">
                <button class="nav-link nav-link-main" data-nav-group="calendar">📅 Calendar <svg width="10" height="6" viewBox="0 0 10 6" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M1 1l4 4 4-4"/></svg></button>
                <div class="nav-dropdown-content">
                    <a href="catalysts.html" class="nav-dropdown-link" data-nav-id="catalysts">🎯 Catalyst Calendar</a>
                    <a href="calendar.html" class="nav-dropdown-link" data-nav-id="calendar">📅 Industry Events</a>
                    <a href="launches.html" class="nav-dropdown-link" data-nav-id="launches">🛰️ Space Launches</a>
                    <a href="earnings-signals.html" class="nav-dropdown-link" data-nav-id="earnings-signals">📈 Earnings Signals</a>
                    <a href="regulatory.html" class="nav-dropdown-link" data-nav-id="regulatory">📋 Regulatory</a>
                </div>
            </div>

            <div class="nav-dropdown">
                <button class="nav-link nav-link-main" data-nav-group="capital">💰 Capital <svg width="10" height="6" viewBox="0 0 10 6" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M1 1l4 4 4-4"/></svg></button>
                <div class="nav-dropdown-content">
                    <a href="investors.html" class="nav-dropdown-link" data-nav-id="investors">👥 Investors</a>
                    <a href="investor-intelligence.html" class="nav-dropdown-link" data-nav-id="investor-intelligence">🕸 Investor Intelligence</a>
                    <a href="investor-hub.html" class="nav-dropdown-link" data-nav-id="investor-hub">💼 Investor Hub</a>
                    <a href="baskets.html" class="nav-dropdown-link" data-nav-id="baskets">💰 Public Baskets</a>
                    <a href="valuations.html" class="nav-dropdown-link" data-nav-id="valuations">📉 Valuations</a>
                    <a href="captable.html" class="nav-dropdown-link" data-nav-id="captable">📋 Cap Tables</a>
                    <a href="govradar.html" class="nav-dropdown-link" data-nav-id="govradar">🎖️ Government Radar</a>
                </div>
            </div>

            <div class="nav-dropdown">
                <button class="nav-link nav-link-main" data-nav-group="signals">🔴 Signals <svg width="10" height="6" viewBox="0 0 10 6" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M1 1l4 4 4-4"/></svg></button>
                <div class="nav-dropdown-content">
                    <a href="brief.html" class="nav-dropdown-link" data-nav-id="brief">📰 Frontier Daily</a>
                    <a href="signals.html" class="nav-dropdown-link" data-nav-id="signals">🔴 Proprietary Signals</a>
                    <a href="discovery.html" class="nav-dropdown-link" data-nav-id="discovery">🌟 Discovery Queue</a>
                    <a href="power-grid.html" class="nav-dropdown-link" data-nav-id="power-grid">⚡ Power Grid</a>
                    <a href="alerts.html" class="nav-dropdown-link" data-nav-id="alerts">🔔 Alerts</a>
                </div>
            </div>

            <div class="nav-dropdown">
                <button class="nav-link nav-link-main" data-nav-group="research">🔬 Research <svg width="10" height="6" viewBox="0 0 10 6" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M1 1l4 4 4-4"/></svg></button>
                <div class="nav-dropdown-content">
                    <a href="visualizations.html" class="nav-dropdown-link" data-nav-id="visualizations">📊 Insights &amp; Data Viz</a>
                    <a href="sectors.html" class="nav-dropdown-link" data-nav-id="sectors">🏭 Sectors</a>
                    <a href="jobs.html" class="nav-dropdown-link" data-nav-id="jobs">💼 Talent</a>
                    <a href="patents.html" class="nav-dropdown-link" data-nav-id="patents">📜 Patents</a>
                    <a href="customers.html" class="nav-dropdown-link" data-nav-id="customers">👥 Customers</a>
                    <a href="compare.html" class="nav-dropdown-link" data-nav-id="compare">⚖️ Compare</a>
                    <a href="transformation.html" class="nav-dropdown-link" data-nav-id="transformation">🌱 Transformation</a>
                    <a href="research.html" class="nav-dropdown-link" data-nav-id="research">🔬 Deep Research</a>
                </div>
            </div>
        </div>
        <div class="nav-auth" id="nav-auth">
            <button class="nav-sign-in-btn" onclick="TILAuth.showAuthModal()">Sign In</button>
            <a href="https://www.rationaloptimistsociety.com" target="_blank" rel="noopener" class="nav-cta">Join ROS</a>
        </div>
        <div class="nav-user" id="nav-user" style="display:none;">
            <span class="nav-user-email" id="nav-user-email"></span>
            <button class="nav-signout-btn" onclick="TILAuth.signOut()">Sign Out</button>
        </div>
        <button class="mobile-menu-btn" aria-label="Menu"><span></span><span></span><span></span></button>
    </nav>'''


# Pages to skip (not user-facing)
SKIP_FILES = {
    "styleguide.html",      # internal preview, has minimal page-specific layout
    "terms.html",           # legal, may have different layout
    "privacy.html",         # legal, may have different layout
}

# Match the existing <nav class="nav">…</nav> block (also handles modifier
# classes like "nav nav-minimal" used by company.html). Preceding HTML
# comment lines that label the nav are also captured for replacement.
NAV_RE = re.compile(
    r'(?:[ \t]*<!--[^\n]*nav[^\n]*-->\s*\n)?'   # optional preceding comment
    r'[ \t]*<nav class="nav(?:\s+[^"]*)?">[\s\S]*?</nav>',
    re.IGNORECASE,
)


def page_id_from_filename(path):
    """Map foo.html → 'foo' (used as data-nav-id)."""
    return path.stem


def highlight_active(nav_html, page_id):
    """Mark the active page's <a> tag with primary-bright color, and the
    parent nav-dropdown's button with the same color so the open menu
    indicates which group the user is currently in."""
    if page_id in {"index", "terminal"}:
        # Top-level direct links
        nav_html = re.sub(
            rf'(<a href="{re.escape(page_id)}\.html"[^>]*data-nav-id="{re.escape(page_id)}")',
            r'\1 aria-current="page"',
            nav_html,
        )
        # For terminal, the inline color stays. For index, add bright color.
        if page_id == "index":
            nav_html = nav_html.replace(
                'data-nav-id="index" aria-current="page"',
                'data-nav-id="index" aria-current="page" style="color:var(--color-primary-bright)"',
            )
        return nav_html

    # Dropdown items — highlight + mark dropdown button + add aria-current
    pattern = rf'(<a href="{re.escape(page_id)}\.html" class="nav-dropdown-link" data-nav-id="{re.escape(page_id)}">)'

    def replace_link(m):
        return m.group(0).replace(
            f'data-nav-id="{page_id}">',
            f'data-nav-id="{page_id}" aria-current="page" style="color:var(--color-primary-bright)">',
        )

    new_html = re.sub(pattern, replace_link, nav_html)

    # Find the parent nav-dropdown block containing this link, and
    # highlight its button text. This requires walking the dropdown
    # blocks in order.
    # Use a state-aware approach.
    return new_html


def update_file(path, dry_run=False):
    """Replace the nav block in `path` with the unified version, preserving
    any modifier classes (e.g. .nav-minimal on company.html)."""
    src = path.read_text(encoding="utf-8")

    page_id = page_id_from_filename(path)
    new_nav = highlight_active(NAV_TEMPLATE, page_id)

    # Preserve modifier classes — capture the original `<nav class="...">`
    # opening tag so we can keep its modifiers (e.g. "nav-minimal").
    m = NAV_RE.search(src)
    if not m:
        return ("skip", "no nav block found")

    old_block = m.group(0)
    nav_class_m = re.search(r'<nav class="(nav(?:\s+[^"]*)?)"', old_block)
    if nav_class_m:
        original_class = nav_class_m.group(1)  # e.g. "nav" or "nav nav-minimal"
        if original_class != "nav":
            new_nav = new_nav.replace('<nav class="nav">', f'<nav class="{original_class}">')

    new_src = src[:m.start()] + new_nav + src[m.end():]
    if new_src == src:
        return ("noop", "already unified")

    if dry_run:
        return ("preview", f"would replace {len(old_block)}B with {len(new_nav)}B")

    path.write_text(new_src, encoding="utf-8")
    return ("ok", f"replaced {len(old_block)}B → {len(new_nav)}B")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    print("=" * 64)
    print("Nav unification (Sprint 5 IA migration)")
    print(f"Mode: {'DRY RUN' if args.dry_run else 'APPLY'}")
    print("=" * 64)

    html_files = sorted([
        p for p in ROOT.glob("*.html")
        if p.name not in SKIP_FILES
    ])

    summary = {"ok": 0, "noop": 0, "skip": 0, "preview": 0}

    for p in html_files:
        status, msg = update_file(p, dry_run=args.dry_run)
        summary[status] = summary.get(status, 0) + 1
        sym = {"ok": "✓", "noop": "·", "skip": "⏭", "preview": "→"}.get(status, "?")
        print(f"  {sym} {p.name:<35} {msg}")

    print()
    print(f"Summary: {summary}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
